#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff_Users
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff_Users/Delete.cshtml")]
    public class Delete : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Delete()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff_Users\Delete.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>");


            
            #line 5 "..\..\Views\Staff_Users\Delete.cshtml"
Write("Delete User");

            
            #line default
            #line hidden
WriteLiteral(" + ");


            
            #line 5 "..\..\Views\Staff_Users\Delete.cshtml"
                  Write(ViewBag.Id);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n<p class=\"");


            
            #line 7 "..\..\Views\Staff_Users\Delete.cshtml"
     Write(Html.AlertWarningClass());

            
            #line default
            #line hidden
WriteLiteral("\">There is no undo!</p>\r\n        <form method=\"post\" action=\"");


            
            #line 8 "..\..\Views\Staff_Users\Delete.cshtml"
                               Write(Url.Action("Delete", "Staff_Users", new { id = ViewBag.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-horizontal\">\r\n            <div class=\"");


            
            #line 9 "..\..\Views\Staff_Users\Delete.cshtml"
                   Write(Html.FormActionsClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <input class=\"btn btn-danger\" value=\"");


            
            #line 10 "..\..\Views\Staff_Users\Delete.cshtml"
                                                 Write("Delete User ");

            
            #line default
            #line hidden
WriteLiteral("\" type=\"submit\" />\r\n            </div>\r\n        </form>");


        }
    }
}
#pragma warning restore 1591
