#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff_Users
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff_Users/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<Staff_Users_Edit>
    {
        public Edit()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Staff_Users\Edit.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "User #" + @Model.Id;


            
            #line default
            #line hidden

            
            #line 6 "..\..\Views\Staff_Users\Edit.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n<form id=\"mainForm\" method=\"post\" action=\"");


            
            #line 7 "..\..\Views\Staff_Users\Edit.cshtml"
                                     Write(Url.Action("Edit", "Staff_Users"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-horizontal\">\r\n");


            
            #line 8 "..\..\Views\Staff_Users\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <fieldset>\r\n        ");


            
            #line 10 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 11 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 12 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 13 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 14 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.ControlGroup(Html.ControlLabel("Is Verified"), @Html.CheckBoxFor(m => m.IsVerified)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 15 "..\..\Views\Staff_Users\Edit.cshtml"
   Write(Html.FormButtons("Update"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </fieldset>\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
