#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Billing.cshtml")]
    public class Billing : System.Web.Mvc.WebViewPage<Account_Subscription>
    {
        public Billing()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\Billing.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    
    ViewData["Heading"] = S.Account_Billing_PageTitle;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.Account_BillingInfo();\r\n");


});

WriteLiteral("\r\n");


            
            #line 12 "..\..\Views\Account\Billing.cshtml"
Write(Html.ValidationSummary("Your billing info couldn't be updated.  Please address the following:"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form method=\"post\" action=\"");


            
            #line 13 "..\..\Views\Account\Billing.cshtml"
                        Write(Url.Action<AccountController>(c => c.Billing()));

            
            #line default
            #line hidden
WriteLiteral("\" id=\"mainForm\" class=\"form-horizontal\">\r\n");


            
            #line 14 "..\..\Views\Account\Billing.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <fieldset>\r\n        ");


            
            #line 16 "..\..\Views\Account\Billing.cshtml"
   Write(Html.TextBoxControlGroupFor(m=>m.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 17 "..\..\Views\Account\Billing.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 18 "..\..\Views\Account\Billing.cshtml"
   Write(Html.ControlGroup(Html.ControlLabelFor(m => m.PostalCode), Html.TextBoxFor(m => m.PostalCode, new { @class= "mini"})));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"");


            
            #line 19 "..\..\Views\Account\Billing.cshtml"
               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 20 "..\..\Views\Account\Billing.cshtml"
       Write(Html.ControlLabelFor(m => m.CreditCardNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"controls\">\r\n                ");


            
            #line 22 "..\..\Views\Account\Billing.cshtml"
           Write(Html.TextBoxFor(m => m.CreditCardNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span class=\"help-block\" id=\"cards-accepted\">");


            
            #line 23 "..\..\Views\Account\Billing.cshtml"
                                                        Write(S.Subscribe_CardsAccepted);

            
            #line default
            #line hidden
WriteLiteral("</span>                \r\n            </div>\r\n        </div>\r\n        ");


            
            #line 26 "..\..\Views\Account\Billing.cshtml"
   Write(Html.ControlGroup(Html.ControlLabelFor(m => m.CreditCardVerificationCode), Html.TextBoxFor(m => m.CreditCardVerificationCode, new { @class = "mini" })));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"");


            
            #line 27 "..\..\Views\Account\Billing.cshtml"
               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 28 "..\..\Views\Account\Billing.cshtml"
       Write(Html.ControlLabel("Expiration", "ccExpiration"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"controls\">\r\n                ");


            
            #line 30 "..\..\Views\Account\Billing.cshtml"
           Write(Html.DropDownListFor(m => m.CreditCardMonth, Model.CreditCardMonths));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 31 "..\..\Views\Account\Billing.cshtml"
           Write(Html.DropDownListFor(m => m.CreditCardYear, Model.CreditCardYears));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        ");


            
            #line 34 "..\..\Views\Account\Billing.cshtml"
   Write(Html.FormButtons(S.Shared_SubmitBtn_Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </fieldset>\r\n</form>");


        }
    }
}
#pragma warning restore 1591
