#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Index-NoAccount.cshtml")]
    public class Index_NoAccount : System.Web.Mvc.WebViewPage<IAccount>
    {
        public Index_NoAccount()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\Index-NoAccount.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    ViewData["Heading"] = S.Account_Index_PageTitle;
    



            
            #line default
            #line hidden
WriteLiteral("\r\n<p>Thanks for being a part of Takeoff.  Right now, you are a guest, most likely" +
" you are here to review some video.  Have a blast!</p>\r\n<p>In this &quot;Account" +
"&quot; section, you can edit your preferences.  If you want, you can <a href=\"");


            
            #line 10 "..\..\Views\Account\Index-NoAccount.cshtml"
                                                                                                  Write(Url.Action<SignupController>(c => c.Index(null, null, null)));

            
            #line default
            #line hidden
WriteLiteral("\">create your very own Takeoff account</a>, which will \r\nlet you create videos an" +
"d add productions.</p>");


        }
    }
}
#pragma warning restore 1591
