#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Layout.cshtml")]
    public class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Account\Layout.cshtml"
  
    Layout = "~/Views/Shared/Layout-Base.cshtml";
    ViewData["MainCssLib"] = "Assets/css/theme.css";

    ViewData.AddBodyCss("app", "account-shell");//account-shell is needed because when using account-area, some pages outside of the shell got wrong css attributes (like signup or /account/demoforbidden).
    this.RedefineSection("CssExternal");
    this.RedefineSection("CssInline");
    this.RedefineSection("JsDocReady");

    var user = ViewData["User"].CastTo<IUser>();
    
    var account = user.Account;
    var hasAccount = account != null;
    var isSubscribed = hasAccount && account.IsSubscribed();
    
    var heading = ViewData["Heading"].CastTo<string>();
    if (heading.HasChars())
    {
        if (ViewData["PageTitle"] == null)
        {
            ViewData["PageTitle"] = heading;
        }
        if (ViewData["IncludeHeadingPrefix"].ValueOr(false))
        {
            heading = S.Account_Shared_PageHeading + heading.StartWith(" - ");
        }
    }



            
            #line default
            #line hidden

DefineSection("JsInline", () => {

WriteLiteral("\r\n");


            
            #line 32 "..\..\Views\Account\Layout.cshtml"
     if (ViewData["Identity"].CastTo<Identity>() != null)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n    $.loginPing();\r\n    ");

WriteLiteral("\r\n");


            
            #line 37 "..\..\Views\Account\Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 38 "..\..\Views\Account\Layout.cshtml"
Write(RenderSection("JsInline", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("JsExternal", () => {

WriteLiteral("\r\n    ");


            
            #line 42 "..\..\Views\Account\Layout.cshtml"
Write(Html.JsLib("interior.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 43 "..\..\Views\Account\Layout.cshtml"
Write(Html.JsLib("app-account.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 44 "..\..\Views\Account\Layout.cshtml"
Write(RenderSection("JsExternal", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<div class=\"container\">\r\n    ");


            
            #line 47 "..\..\Views\Account\Layout.cshtml"
Write(RenderPage("~/Views/Shared/Layout-Nav.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div id=\"main-content-container\" role=\"main\">\r\n        <div class=\"page-h" +
"eader\">\r\n    \t    <h1>");


            
            #line 51 "..\..\Views\Account\Layout.cshtml"
        Write(heading);

            
            #line default
            #line hidden
WriteLiteral("</h1>    \r\n        </div>\r\n        ");


            
            #line 53 "..\..\Views\Account\Layout.cshtml"
   Write(RenderPage("~/Views/Shared/Layout-NagBanners.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 55 "..\..\Views\Account\Layout.cshtml"
         if (IsSectionDefined("AfterHeader"))
        {
            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Account\Layout.cshtml"
       Write(RenderSection("AfterHeader"));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Account\Layout.cshtml"
                                         
        }

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"container-fluid\">\r\n            <div class=\"row-fluid\">\r\n     " +
"           <div class=\"span3\">\r\n                    <nav class=\"account-nav well" +
"\">\r\n                    <ul class=\"nav nav-list\">\r\n                        <li><" +
"a href=\"");


            
            #line 64 "..\..\Views\Account\Layout.cshtml"
                                 Write(Url.Action<AccountController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 64 "..\..\Views\Account\Layout.cshtml"
                                                                                   Write(Html.ClassAttIfAction<AccountController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 64 "..\..\Views\Account\Layout.cshtml"
                                                                                                                                                          Write(S.Account_Shared_SideNav_Summary_Text);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                        <li><a href=\"");


            
            #line 65 "..\..\Views\Account\Layout.cshtml"
                                 Write(Url.Action<AccountController>(c => c.MainInfo()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 65 "..\..\Views\Account\Layout.cshtml"
                                                                                      Write(Html.ClassAttIfAction<AccountController>("selected", c => c.MainInfo()));

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 65 "..\..\Views\Account\Layout.cshtml"
                                                                                                                                                                Write(S.Account_Shared_SideNav_PersonalInfo_Text);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 66 "..\..\Views\Account\Layout.cshtml"
                         if (hasAccount)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 68 "..\..\Views\Account\Layout.cshtml"
                                     Write(Url.Action<AccountController>(c => c.Logo()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 68 "..\..\Views\Account\Layout.cshtml"
                                                                                      Write(Html.ClassAttIfAction<AccountController>("selected", c => c.Logo()));

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 68 "..\..\Views\Account\Layout.cshtml"
                                                                                                                                                            Write(S.Account_Shared_SideNav_Logo_Text);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 69 "..\..\Views\Account\Layout.cshtml"
                        }

            
            #line default
            #line hidden

            
            #line 70 "..\..\Views\Account\Layout.cshtml"
                         if (isSubscribed)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 72 "..\..\Views\Account\Layout.cshtml"
                                     Write(Url.Action<AccountController>(c => c.Billing()));

            
            #line default
            #line hidden
WriteLiteral("\"  ");


            
            #line 72 "..\..\Views\Account\Layout.cshtml"
                                                                                          Write(Html.ClassAttIfAction<AccountController>("selected", c => c.Billing()));

            
            #line default
            #line hidden
WriteLiteral(">Billing Information</a></li>\r\n");


            
            #line 73 "..\..\Views\Account\Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li><a href=\"");


            
            #line 74 "..\..\Views\Account\Layout.cshtml"
                                 Write(Url.Action<AccountNotificationsController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 74 "..\..\Views\Account\Layout.cshtml"
                                                                                                Write(Html.ClassAttIfAction<AccountNotificationsController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">Email Notifications</a></li>\r\n                        <li><a href=\"");


            
            #line 75 "..\..\Views\Account\Layout.cshtml"
                                 Write(Url.Action<AccountController>(c => c.Privacy()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 75 "..\..\Views\Account\Layout.cshtml"
                                                                                     Write(Html.ClassAttIfAction<AccountController>("selected", c => c.Privacy()));

            
            #line default
            #line hidden
WriteLiteral(">Privacy Settings</a></li>\r\n");


            
            #line 76 "..\..\Views\Account\Layout.cshtml"
                         if (hasAccount)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 78 "..\..\Views\Account\Layout.cshtml"
                                     Write(Url.Action<AccountMembersController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 78 "..\..\Views\Account\Layout.cshtml"
                                                                                              Write(Html.ClassAttIfAction<AccountMembersController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">My Members</a></li>\r\n");


            
            #line 79 "..\..\Views\Account\Layout.cshtml"
                            if (account.Status != AccountStatus.TrialAnonymous && account.Status != AccountStatus.Trial2)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 81 "..\..\Views\Account\Layout.cshtml"
                                         Write(Url.Action<AccountPlanController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 81 "..\..\Views\Account\Layout.cshtml"
                                                                                               Write(Html.ClassAttIfAction<AccountPlanController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">Change Plan</a></li>\r\n");


            
            #line 82 "..\..\Views\Account\Layout.cshtml"
                            }
                            if (isSubscribed)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li><a href=\"");


            
            #line 85 "..\..\Views\Account\Layout.cshtml"
                                         Write(Url.Action<InvoicesController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 85 "..\..\Views\Account\Layout.cshtml"
                                                                                            Write(Html.ClassAttIfAction<InvoicesController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">Invoices</a></li>\r\n");


            
            #line 86 "..\..\Views\Account\Layout.cshtml"
                            }
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a href=\"");


            
            #line 90 "..\..\Views\Account\Layout.cshtml"
                                     Write(Url.Action<SignupController>(c => c.Index(null, null, null)));

            
            #line default
            #line hidden
WriteLiteral("\">Get My Own Account</a></li>  \r\n");


            
            #line 91 "..\..\Views\Account\Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li><a href=\"");


            
            #line 92 "..\..\Views\Account\Layout.cshtml"
                                 Write(Url.Action<AccountMembershipsController>(c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 92 "..\..\Views\Account\Layout.cshtml"
                                                                                              Write(Html.ClassAttIfAction<AccountMembershipsController>("selected", c => c.Index()));

            
            #line default
            #line hidden
WriteLiteral(">Associated Accounts</a></li>\r\n                        <li><a  href=\"");


            
            #line 93 "..\..\Views\Account\Layout.cshtml"
                                  Write(Url.Action<AccountController>(c => c.Close()));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 93 "..\..\Views\Account\Layout.cshtml"
                                                                                    Write(Html.ClassAttIfAction<AccountController>("selected", c => c.Close()));

            
            #line default
            #line hidden
WriteLiteral(">Close My Account</a></li>\r\n                    </ul>\r\n                    </nav>" +
"        \r\n                </div>\r\n                <div class=\"span9\" id=\"main-co" +
"ntent\">\r\n                    ");


            
            #line 98 "..\..\Views\Account\Layout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n<footer" +
">\r\n    <p>");


            
            #line 104 "..\..\Views\Account\Layout.cshtml"
  Write(S.Footer_Copyright.FormatResource(DateTime.Now.Year.ToInvariant()));

            
            #line default
            #line hidden
WriteLiteral(" &nbsp; ");


            
            #line 104 "..\..\Views\Account\Layout.cshtml"
                                                                             Write(S.Footer_SupportLink.FormatResource(Html.StartActionLink("Index", "Support")));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n</footer>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
