#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Logo.cshtml")]
    public class Logo : System.Web.Mvc.WebViewPage<Account_Logo>
    {
        public Logo()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\Logo.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    ViewData["Heading"] = "Account Logo";
    


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.Account_Logo();\r\n");


});

WriteLiteral("\r\n<p>");


            
            #line 11 "..\..\Views\Account\Logo.cshtml"
Write("This logo will replace the Takeoff logo up top for you and your clients.  In each production, you can also add an accompanying production-specific logo.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 12 "..\..\Views\Account\Logo.cshtml"
Write(Html.ValidationSummary(S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form id=\"logo-form\" method=\"post\" enctype=\"multipart/form-data\" action=\"");


            
            #line 13 "..\..\Views\Account\Logo.cshtml"
                                                                     Write(Url.Action<AccountController>(c => c.Logo()));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-horizontal\">\r\n");


            
            #line 14 "..\..\Views\Account\Logo.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <fieldset>\r\n        <div class=\"");


            
            #line 16 "..\..\Views\Account\Logo.cshtml"
               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 17 "..\..\Views\Account\Logo.cshtml"
       Write(Html.ControlLabel("New Logo", "Logo"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 18 "..\..\Views\Account\Logo.cshtml"
       Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <input type=\"file\" id=\"Logo\" name=\"Logo\" size=\"30\" />          " +
"      \r\n            ");


            
            #line 20 "..\..\Views\Account\Logo.cshtml"
       Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        ");


            
            #line 22 "..\..\Views\Account\Logo.cshtml"
   Write(Html.FormButtons(S.Account_MainInfo_SubmitBtn_Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </fieldset>\r\n</form>\r\n\r\n");


            
            #line 26 "..\..\Views\Account\Logo.cshtml"
 if (true)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"well\">\n        <h3>");


            
            #line 29 "..\..\Views\Account\Logo.cshtml"
        Write("Delete my Logo");

            
            #line default
            #line hidden
WriteLiteral("</h3>\n        <p>");


            
            #line 30 "..\..\Views\Account\Logo.cshtml"
       Write("You and your account members will see Takeoff's regular logo at the top of the page.");

            
            #line default
            #line hidden
WriteLiteral("</p>\n            <form method=\"POST\" action=\"");


            
            #line 31 "..\..\Views\Account\Logo.cshtml"
                                    Write(Url.Action<AccountController>(c => c.Logo()));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 32 "..\..\Views\Account\Logo.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <input type=\"submit\" value=\"Delete\" class=\"btn btn-danger\"/>\r\n " +
"           </form>\n    </div>\r\n");


            
            #line 36 "..\..\Views\Account\Logo.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
