#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/MainInfo.cshtml")]
    public class MainInfo : System.Web.Mvc.WebViewPage<Account_MainInfo>
    {
        public MainInfo()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\MainInfo.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    
    ViewData["Heading"] = S.Account_MainInfo_PageTitle;


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.Account_MainInfo();\r\n");


});

WriteLiteral("\r\n");


            
            #line 11 "..\..\Views\Account\MainInfo.cshtml"
Write(Html.ValidationSummary(S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form id=\"mainForm\" method=\"post\" action=\"");


            
            #line 12 "..\..\Views\Account\MainInfo.cshtml"
                                      Write(Url.Action<AccountController>(c => c.MainInfo()));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-horizontal\">\r\n");


            
            #line 13 "..\..\Views\Account\MainInfo.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <fieldset>\r\n        ");


            
            #line 15 "..\..\Views\Account\MainInfo.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.FirstName, S.Account_MainInfo_FirstName_Label));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 16 "..\..\Views\Account\MainInfo.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.LastName, S.Account_MainInfo_LastName_Label));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 17 "..\..\Views\Account\MainInfo.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.Email, S.Account_MainInfo_Email_Label));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div class=\"");


            
            #line 19 "..\..\Views\Account\MainInfo.cshtml"
               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 20 "..\..\Views\Account\MainInfo.cshtml"
       Write(Html.ControlLabelFor(m => m.CurrentPassword, S.Account_MainInfo_CurrentPassword_Label, S.Account_MainInfo_CurrentPassword_Tooltip));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"controls\">\r\n                ");


            
            #line 22 "..\..\Views\Account\MainInfo.cshtml"
           Write(Html.TextBoxFor(m => m.CurrentPassword, new { type = "password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <label for=\"CurrentPassword\" class=\"tooltip\" style=\"display:non" +
"e;\">");


            
            #line 23 "..\..\Views\Account\MainInfo.cshtml"
                                                                              Write(S.Account_MainInfo_CurrentPassword_Tooltip);

            
            #line default
            #line hidden
WriteLiteral("</label>                \r\n            </div>\r\n        </div>\r\n        ");


            
            #line 26 "..\..\Views\Account\MainInfo.cshtml"
   Write(Html.ControlGroup(Html.ControlLabelFor(m => m.NewPassword, S.Account_MainInfo_NewPassword_Label),Html.TextBoxFor(m => m.NewPassword, new { type = "password" })));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 27 "..\..\Views\Account\MainInfo.cshtml"
   Write(Html.FormButtons(S.Account_MainInfo_SubmitBtn_Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </fieldset>\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
