#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/NecessaryInfo.cshtml")]
    public class NecessaryInfo : System.Web.Mvc.WebViewPage<Account_NecessaryInfo>
    {
        public NecessaryInfo()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\NecessaryInfo.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
    ViewData["PageTitle"] = S.Account_NecessaryInfo_PageTitle;
    ViewData["EnableNagBanner"] = false;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("JsExternal", () => {

WriteLiteral("\r\n    ");


            
            #line 11 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.JsLib("app-account.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.Account_NecessaryInfo();\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 21 "..\..\Views\Account\NecessaryInfo.cshtml"
   Write(S.Account_NecessaryInfo_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n<p class=\"");


            
            #line 23 "..\..\Views\Account\NecessaryInfo.cshtml"
     Write(Html.FormInstructionsClass());

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 23 "..\..\Views\Account\NecessaryInfo.cshtml"
                                    Write(S.Account_NecessaryInfo_Explanation);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 24 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.ValidationSummary(S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form action=\"");


            
            #line 25 "..\..\Views\Account\NecessaryInfo.cshtml"
          Write(Url.Action<AccountController>(c=> c.NecessaryInfo((Account_NecessaryInfo)null)));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" class=\"form-horizontal\">\r\n    ");


            
            #line 26 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 27 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.HiddenFor(m => m.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 28 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.HiddenFor(m => m.TimezoneOffset));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "..\..\Views\Account\NecessaryInfo.cshtml"
 if (Model.FirstName.HasNoChars())
{
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.TextBoxControlGroupFor(m => m.FirstName));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Account\NecessaryInfo.cshtml"
                                                  
}

            
            #line default
            #line hidden

            
            #line 33 "..\..\Views\Account\NecessaryInfo.cshtml"
 if (Model.LastName.HasNoChars())
{
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.TextBoxControlGroupFor(m => m.LastName));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Account\NecessaryInfo.cshtml"
                                                 
}

            
            #line default
            #line hidden

            
            #line 37 "..\..\Views\Account\NecessaryInfo.cshtml"
 if (Model.Password == null)
{
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.PasswordControlGroupFor(m => m.Password));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Account\NecessaryInfo.cshtml"
                                                  
    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.PasswordControlGroup(S.PasswordReset_PasswordConfirmLabel, "passwordConfirm", "passwordConfirm"));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Account\NecessaryInfo.cshtml"
                                                                                                          
}

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"");


            
            #line 42 "..\..\Views\Account\NecessaryInfo.cshtml"
           Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 43 "..\..\Views\Account\NecessaryInfo.cshtml"
   Write(Html.ControlLabel(S.Signup_Account_Form_SignupSource_Label, "SignupSource"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"controls\">\r\n            <select id=\"SignupSource\" name=\"Sig" +
"nupSource\">\r\n                <option value=\"\"></option>\r\n                <option" +
" value=\"WordOfMouth\">");


            
            #line 47 "..\..\Views\Account\NecessaryInfo.cshtml"
                                       Write(S.Signup_Account_Form_SignupSource_WordOfMouth);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option value=\"Email\">");


            
            #line 48 "..\..\Views\Account\NecessaryInfo.cshtml"
                                 Write(S.Signup_Account_Form_SignupSource_Email);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option value=\"SearchEngine\">");


            
            #line 49 "..\..\Views\Account\NecessaryInfo.cshtml"
                                        Write(S.Signup_Account_Form_SignupSource_SearchEngine);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option value=\"MessageForum\">");


            
            #line 50 "..\..\Views\Account\NecessaryInfo.cshtml"
                                        Write(S.Signup_Account_Form_SignupSource_MessageForum);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n                <option value=\"Other\">");


            
            #line 51 "..\..\Views\Account\NecessaryInfo.cshtml"
                                 Write(S.Signup_Account_Form_SignupSource_Other);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n            </select>            \r\n        </div>\r\n    </div>\r\n    ");


            
            #line 55 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.ControlGroup(Html.ControlLabelFor(m => m.SignupSourceOther, @S.Signup_Account_Form_SignupSourceOther_Label), @Html.TextBoxFor(m => m.SignupSourceOther), "hide","SignupSourceOther-container"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");


            
            #line 57 "..\..\Views\Account\NecessaryInfo.cshtml"
Write(Html.FormButtons(S.Shared_UpdateBtn_Text));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
