#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/PasswordReset.cshtml")]
    public class PasswordReset : System.Web.Mvc.WebViewPage<Account_PasswordReset>
    {
        public PasswordReset()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\PasswordReset.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
    ViewData["PageTitle"] = S.PasswordReset_PageTitle;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral(@"
    $(""#main-content form"").madValidate({
        rules:
        {
            NewPassword: {
                required: true
            },
            passwordConfirm: {
                required: true,
                equalTo: ""#NewPassword""
            }
        },
        useAjax: false
    });
");


});

WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n\t<h1>");


            
            #line 26 "..\..\Views\Account\PasswordReset.cshtml"
Write(S.PasswordReset_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 29 "..\..\Views\Account\PasswordReset.cshtml"
Write(Html.ValidationSummary(S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form action=\"");


            
            #line 30 "..\..\Views\Account\PasswordReset.cshtml"
          Write(Url.Action<AccountController>(c => c.PasswordResetPost(null)));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" class=\"form-horizontal\">\r\n    ");


            
            #line 31 "..\..\Views\Account\PasswordReset.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 32 "..\..\Views\Account\PasswordReset.cshtml"
Write(Html.HiddenFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 33 "..\..\Views\Account\PasswordReset.cshtml"
Write(Html.HiddenFor(m => m.ResetKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 34 "..\..\Views\Account\PasswordReset.cshtml"
Write(Html.ControlGroup(Html.ControlLabelFor(m => m.NewPassword, S.PasswordReset_PasswordLabel), Html.PasswordFor(m => m.NewPassword)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"");


            
            #line 35 "..\..\Views\Account\PasswordReset.cshtml"
           Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 36 "..\..\Views\Account\PasswordReset.cshtml"
   Write(Html.ControlLabel(S.PasswordReset_PasswordConfirmLabel, "passwordConfirm"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 37 "..\..\Views\Account\PasswordReset.cshtml"
   Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input type=\"password\" name=\"passwordConfirm\" id=\"passwordConfirm\" />\r\n" +
"        ");


            
            #line 39 "..\..\Views\Account\PasswordReset.cshtml"
   Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"");


            
            #line 41 "..\..\Views\Account\PasswordReset.cshtml"
           Write(Html.FormActionsClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 42 "..\..\Views\Account\PasswordReset.cshtml"
   Write(Html.SubmitButton(S.PasswordReset_SubmitBtnText));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
