#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Account
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/PasswordReset-Request.cshtml")]
    public class PasswordReset_Request : System.Web.Mvc.WebViewPage<Account_PasswordReset>
    {
        public PasswordReset_Request()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Account\PasswordReset-Request.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
    ViewData["PageTitle"] = S.PasswordResetRequest_PageTitle;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral(@"

    $(""#main-content form"").madValidate({
        rules:
        {
            Email: {
                required: true,
                email: true
            }
        },
        useAjax: false
    });

    $(""#main-content form input[type='password']"").val("""");
");


});

WriteLiteral("\r\n\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n\t<h1>");


            
            #line 27 "..\..\Views\Account\PasswordReset-Request.cshtml"
Write(S.PasswordResetRequest_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 30 "..\..\Views\Account\PasswordReset-Request.cshtml"
Write(Html.ValidationSummary(S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n<form action=\"");


            
            #line 31 "..\..\Views\Account\PasswordReset-Request.cshtml"
          Write(Url.Action<AccountController>(c => c.PasswordResetPost(null)));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" class=\"form-horizontal\">\r\n    ");


            
            #line 32 "..\..\Views\Account\PasswordReset-Request.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 33 "..\..\Views\Account\PasswordReset-Request.cshtml"
Write(Html.TextBoxControlGroupFor(m => m.Email, S.PasswordReset_EmailLabel));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 34 "..\..\Views\Account\PasswordReset-Request.cshtml"
Write(Html.FormButtons(S.PasswordResetRequest_SubmitBtnText));

            
            #line default
            #line hidden
WriteLiteral("\r\n</form>\r\n");


        }
    }
}
#pragma warning restore 1591
