#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Productions
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Productions/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<Production_Details>
    {
        public Details()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Productions\Details.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Medium.cshtml";
    ViewData.AddBodyCss("production-details");
    var showSettings = Model.Data.CanEdit || Model.IsMember || Model.Data.CanDelete;
    ViewData["PageTitle"] = Model.Data.Title;
    if ( !Model.IsMember)
    {
        ViewData.AddBodyCss("not-logged-in");
    }


            
            #line default
            #line hidden

DefineSection("JsExternal", () => {

WriteLiteral("\r\n    ");


            
            #line 14 "..\..\Views\Productions\Details.cshtml"
Write(Html.JsLib("interior.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 15 "..\..\Views\Productions\Details.cshtml"
Write(Html.JsLib("productions-details.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"//api.filepicker.io/v1/filepicker.js\"><" +
"/script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    productionData = ");


            
            #line 20 "..\..\Views\Productions\Details.cshtml"
                Write(Html.Json(Model.Data));

            
            #line default
            #line hidden
WriteLiteral("; \r\n");


            
            #line 21 "..\..\Views\Productions\Details.cshtml"
     if (Model.SemiAnonymousUserName.HasChars())
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n    productionData.SemiAnonymousUserName = ");


            
            #line 24 "..\..\Views\Productions\Details.cshtml"
                                      Write(Html.Json(Model.SemiAnonymousUserName));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        ");

WriteLiteral("\r\n");


            
            #line 26 "..\..\Views\Productions\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    preferHtml5Video = ");


            
            #line 27 "..\..\Views\Productions\Details.cshtml"
                  Write(Html.Json(Model.PreferHtml5Video));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    filepicker.setKey(");


            
            #line 28 "..\..\Views\Productions\Details.cshtml"
                 Write(Html.Json(Model.FilePickerApiKey));

            
            #line default
            #line hidden
WriteLiteral(");\r\n");


            
            #line 29 "..\..\Views\Productions\Details.cshtml"
     if (Model.InitialFocus.HasChars())
    {        

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n        initialFocus = \'");


            
            #line 32 "..\..\Views\Productions\Details.cshtml"
                   Write(Model.InitialFocus);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        ");

WriteLiteral("\r\n");


            
            #line 34 "..\..\Views\Productions\Details.cshtml"
    }    

            
            #line default
            #line hidden

            
            #line 35 "..\..\Views\Productions\Details.cshtml"
     if (!Model.EnableChangeSyncing)
    {        

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n        enableChangeSyncing = false;\r\n        ");

WriteLiteral("\r\n");


            
            #line 40 "..\..\Views\Productions\Details.cshtml"
    }else
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n        activityInterval = ");


            
            #line 43 "..\..\Views\Productions\Details.cshtml"
                      Write(Html.Json(Convert.ToInt64(Model.ActivityInterval.TotalMilliseconds)));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        ");

WriteLiteral("\r\n");


            
            #line 45 "..\..\Views\Productions\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    initProductionUi();\r\n    printCssUrl = ");


            
            #line 47 "..\..\Views\Productions\Details.cshtml"
             Write(Html.Json(Url.Asset("Assets/css/printing.css")));

            
            #line default
            #line hidden
WriteLiteral(";\r\n");


});

WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>\r\n");


            
            #line 52 "..\..\Views\Productions\Details.cshtml"
     if (Model.Data.Logo != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <img src=\"");


            
            #line 54 "..\..\Views\Productions\Details.cshtml"
             Write(Model.Data.Logo.Url);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Logo\" style=\"width:");


            
            #line 54 "..\..\Views\Productions\Details.cshtml"
                                                           Write(Model.Data.Logo.Width.ToInvariant());

            
            #line default
            #line hidden
WriteLiteral("px;height:");


            
            #line 54 "..\..\Views\Productions\Details.cshtml"
                                                                                                         Write(Model.Data.Logo.Height.ToInvariant());

            
            #line default
            #line hidden
WriteLiteral("px;\" />\r\n");


            
            #line 55 "..\..\Views\Productions\Details.cshtml"
    }    

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 56 "..\..\Views\Productions\Details.cshtml"
Write(Model.Data.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h1>\r\n");


});

WriteLiteral("\r\n<ul id=\"mainTabs\" class=\"nav nav-tabs\">\r\n    <li id=\"videos-tab\"><a href=\"#\">");


            
            #line 60 "..\..\Views\Productions\Details.cshtml"
                                Write("Videos");

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n    <li id=\"files-tab\"><a href=\"#\">");


            
            #line 61 "..\..\Views\Productions\Details.cshtml"
                               Write("Assets");

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n    <li id=\"members-tab\"><a href=\"#\">");


            
            #line 62 "..\..\Views\Productions\Details.cshtml"
                                 Write("Team");

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n    <li id=\"settings-tab\" ");


            
            #line 63 "..\..\Views\Productions\Details.cshtml"
                     Write(Html.Raw(showSettings ? string.Empty : "style=\"display:none !important;\""));

            
            #line default
            #line hidden
WriteLiteral("><a href=\"#\">");


            
            #line 63 "..\..\Views\Productions\Details.cshtml"
                                                                                                                Write("Settings");

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n</ul>\r\n<div class=\"row\" id=\"mainTabs-panels\">\r\n<div id=\"mainArea\" clas" +
"s=\"span8\">\r\n    <div class=\"background\">\r\n    </div>\r\n    <div id=\"videosArea\" c" +
"lass=\"tabPane\">\r\n        <h2>");


            
            #line 70 "..\..\Views\Productions\Details.cshtml"
        Write("Videos");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 71 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddVideo)
                    {                   

            
            #line default
            #line hidden
WriteLiteral("                    <div>\r\n                        <a href=\"#\" class=\"btn\" id=\"vi" +
"deo-add-button\">");


            
            #line 74 "..\..\Views\Productions\Details.cshtml"
                                                                  Write("Add Video");

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </div>\r\n");


            
            #line 76 "..\..\Views\Productions\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("        </h2>\r\n");


            
            #line 78 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddVideo)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div id=\"video-add\">\r\n                    </div>\r\n");


            
            #line 82 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 83 "..\..\Views\Productions\Details.cshtml"
         if (Model.Data.CanAddVideo)
            {              

            
            #line default
            #line hidden
WriteLiteral("                <ul id=\"videoUploadQueue\" class=\"fileUploadQueue\">\r\n             " +
"   </ul>\r\n");


            
            #line 87 "..\..\Views\Productions\Details.cshtml"

            
            #line default
            #line hidden

            
            #line 90 "..\..\Views\Productions\Details.cshtml"
                  }

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"videosListEmptyMsg\" class=\"empty-data-msg ");


            
            #line 91 "..\..\Views\Productions\Details.cshtml"
                                                          Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 92 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddVideo)
                {        
                    
            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Productions\Details.cshtml"
                Write("No videos have been uploaded yet. Want to upload one?  Click the \"Upload a Video\" button above.");

            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Productions\Details.cshtml"
                                                                                                                          
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Productions\Details.cshtml"
                Write("No videos have been uploaded yet.  When one is available, it will show up here and you'll also get an email.");

            
            #line default
            #line hidden
            
            #line 98 "..\..\Views\Productions\Details.cshtml"
                                                                                                                                     
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <ul id=\"videosList\" class=\"thumbnails\">\r\n        " +
"    </ul>\r\n    </div>\r\n    <div id=\"filesArea\" class=\"tabPane\">\r\n        <h2>");


            
            #line 105 "..\..\Views\Productions\Details.cshtml"
        Write("Asset Files");

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n\r\n\r\n");


            
            #line 109 "..\..\Views\Productions\Details.cshtml"
             if (Model.Data.CanAddFile)
            {                   

            
            #line default
            #line hidden
WriteLiteral("            <div><a href=\"#\" id=\"file-add-button\" class=\"btn\">");


            
            #line 111 "..\..\Views\Productions\Details.cshtml"
                                                          Write("Upload a File");

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n");


            
            #line 112 "..\..\Views\Productions\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </h2>\r\n");


            
            #line 114 "..\..\Views\Productions\Details.cshtml"
         if (Model.Data.CanAddFile)
        {               

            
            #line default
            #line hidden
WriteLiteral("        <ul class=\"fileUploadQueue\" id=\"fileUploadQueue\">\r\n        </ul>         " +
"   \r\n");


            
            #line 118 "..\..\Views\Productions\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div id=\"filesTableEmptyMsg\" class=\"empty-data-msg ");


            
            #line 119 "..\..\Views\Productions\Details.cshtml"
                                                      Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 120 "..\..\Views\Productions\Details.cshtml"
        Write("There aren't any files right now.");

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
            <table id=""filesTable"" cellspacing=""0"" class=""data table table-striped"">
                <thead>
                    <tr>
                        <th>Name</th><th>Size</th><th>Added&nbsp;By</th><th>Added</th><th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
    </div>
    <div id=""membersArea"" class=""tabPane"">
                <h2>Team
");


            
            #line 134 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddMember)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"#\" id=\"newMemberBtn\" class=\"btn\">");


            
            #line 136 "..\..\Views\Productions\Details.cshtml"
                                                          Write("Invite Someone");

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 137 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                    </h2>\r\n");


            
            #line 139 "..\..\Views\Productions\Details.cshtml"
             if (Model.Data.CanAddMember)
            {
               

            
            #line default
            #line hidden
WriteLiteral("                <form id=\"member-add-form\" action=\"");


            
            #line 142 "..\..\Views\Productions\Details.cshtml"
                                              Write(Url.Action("Invite", "ProductionMembers"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"form-horizontal\">\r\n                    <fieldset>\r\n                     " +
"   <div class=\"");


            
            #line 144 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 145 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlLabel("Email or Name", "newMemberNameEmail", "If you've used Takeoff with this person in the past, just start typing their name or email address and it should show up. Otherwise, enter the person's email and we'll take it from there."));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 146 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <input type=\"text\" class=\"span4\" id=\"newMemberN" +
"ameEmail\" name=\"newMemberNameEmail\" />\r\n                            ");


            
            #line 148 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div class=\"");


            
            #line 150 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 151 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlLabel("Role"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 152 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <label class=\"radio\">\r\n                        " +
"            <input id=\"role1\" type=\"radio\" name=\"role\" value=\"Client\" checked=\"c" +
"hecked\" />\r\n                                    ");


            
            #line 155 "..\..\Views\Productions\Details.cshtml"
                                Write("Client");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    ");


            
            #line 156 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlTooltip("Can add comments and upload files, but cannot add new videos or invite people in. Use this for customers and reviewers."));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n                                <labe" +
"l class=\"radio\">\r\n                                    <input id=\"role1\" type=\"ra" +
"dio\" name=\"role\" value=\"Staff\"  />\r\n                                    ");


            
            #line 160 "..\..\Views\Productions\Details.cshtml"
                                Write("Staff");

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    ");


            
            #line 161 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlTooltip("Can add comments, upload files, add new teammates and upload new videos. Use this for editors and contractors."));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </label>\r\n                            ");


            
            #line 163 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div class=\"");


            
            #line 165 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 166 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlLabel("Personal Note", "newMemberNoteInput"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 167 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <textarea id=\"newMemberNoteInput\" class=\"span4\" nam" +
"e=\"note\" rows=\"2\"></textarea>\r\n                            ");


            
            #line 169 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        </div>\r\n                        \r\n                   " +
"     <div class=\"form-actions\">\r\n                            <input type=\"submit" +
"\" class=\"");


            
            #line 174 "..\..\Views\Productions\Details.cshtml"
                                                   Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" value=\"Add\" />\r\n                            <a class=\"cancelBtn btn\" href=\"#\">");


            
            #line 175 "..\..\Views\Productions\Details.cshtml"
                                                          Write("Cancel");

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                        </div>\r\n                    </fieldset>\r\n          " +
"      </form>\r\n");


            
            #line 179 "..\..\Views\Productions\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"membersTableEmptyMsg\" class=\"empty-data-msg ");


            
            #line 180 "..\..\Views\Productions\Details.cshtml"
                                                            Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 181 "..\..\Views\Productions\Details.cshtml"
            Write("There aren't any team members right now.");

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <table id=\"membersTable\" class=\"data table tabl" +
"e-striped\" cellspacing=\"0\">\r\n                <thead>\r\n                    <tr cl" +
"ass=\"hidden\">\r\n                        <th>");


            
            #line 186 "..\..\Views\Productions\Details.cshtml"
                        Write("Name");

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");


            
            #line 187 "..\..\Views\Productions\Details.cshtml"
                        Write("Status");

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th></th>\r\n                    </tr>\r\n            " +
"    </thead>\r\n                <tbody>\r\n                </tbody>\r\n            </t" +
"able>\r\n    </div>\r\n    <div id=\"settingsArea\" class=\"tabPane\" ");


            
            #line 195 "..\..\Views\Productions\Details.cshtml"
                                      Write(Html.Raw(showSettings ? string.Empty : "style=\"display:none !important;\""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <h2>");


            
            #line 196 "..\..\Views\Productions\Details.cshtml"
                Write("Production Settings");

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");


            
            #line 197 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanEdit)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"well\">\r\n                        <h3>Change Settin" +
"gs</h3>\r\n                        ");


            
            #line 201 "..\..\Views\Productions\Details.cshtml"
                   Write(Html.ValidationSummary(@S.Validation_SummaryHeading));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <form id=\"settingsForm\" method=\"post\" action=\"");


            
            #line 202 "..\..\Views\Productions\Details.cshtml"
                                                                 Write(Url.Action("Edit", "Productions", Model.Data.Id));

            
            #line default
            #line hidden
WriteLiteral("\" enctype=\"multipart/form-data\"  class=\"form-horizontal\">\r\n                      " +
"  ");


            
            #line 203 "..\..\Views\Productions\Details.cshtml"
                   Write(Html.Hidden("id", Model.Data.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <fieldset>\r\n                            <div id=\"nameAr" +
"ea\" class=\"");


            
            #line 205 "..\..\Views\Productions\Details.cshtml"
                                                 Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 206 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlLabel("Title", "settingsFormTitle"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 207 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input type=\"text\" id=\"settingsFormTitle\" n" +
"ame=\"Title\" value=\"");


            
            #line 208 "..\..\Views\Productions\Details.cshtml"
                                                                                             Write(Html.Attribute(Model.Data.Title));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                ");


            
            #line 209 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("                                \r\n                            </div>\r\n           " +
"                 <div class=\"");


            
            #line 211 "..\..\Views\Productions\Details.cshtml"
                                   Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 212 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlLabel("Logo", "Logo-Input"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");


            
            #line 213 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input type=\"file\" id=\"Logo-Input\" name=\"Lo" +
"go\" size=\"40\" />\r\n                                ");


            
            #line 215 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("                                \r\n                                \r\n             " +
"               </div>\r\n                            <div id=\"CustomUrl-group\" cla" +
"ss=\"");


            
            #line 218 "..\..\Views\Productions\Details.cshtml"
                                                        Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 219 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlLabel("Custom Url", "CustomUrl", "A custom web address for this production makes it easier to find and share.  For example, enter 'mymovie' and this production can be found at http://takeoffvideo.com/mymovie."));

            
            #line default
            #line hidden
WriteLiteral("\r\n    \r\n                                ");


            
            #line 221 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <div class=\"input-prepend\">\r\n              " +
"                          <span class=\"add-on\">");


            
            #line 223 "..\..\Views\Productions\Details.cshtml"
                                                         Write("http://takeoffvideo.com/");

            
            #line default
            #line hidden
WriteLiteral("</span><input type=\"text\" size=\"16\" id=\"CustomUrl\" name=\"CustomUrl\" class=\"span2\"" +
" value=\"");


            
            #line 223 "..\..\Views\Productions\Details.cshtml"
                                                                                                                                                                              Write(Model.CustomUrl);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                    </div>\r\n                               " +
" ");


            
            #line 225 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("                               \r\n                            </div>\r\n            " +
"                <div id=\"SemiAnonymousLogin-Container\" class=\"");


            
            #line 227 "..\..\Views\Productions\Details.cshtml"
                                                                     Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 228 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlLabel("Guest Password", "QuickAccessDecryptedPassword", "Setting this password lets people enter the production without creating a Takeoff account.  You can optionally allow those people to add comments."));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    ");


            
            #line 229 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.ControlsWrapperBeginTag());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    ");


            
            #line 230 "..\..\Views\Productions\Details.cshtml"
                               Write(Html.TextBoxFor(m => m.QuickAccessDecryptedPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <div class=\"input\" id=\"SemiAnonymousUsersCa" +
"nComment-Container\" style=\"visibility:hidden\">");


            
            #line 231 "..\..\Views\Productions\Details.cshtml"
                                                                                                                        Write(Html.CheckBoxFor(m => m.QuickAccessAllowCommenting));

            
            #line default
            #line hidden
WriteLiteral("Visitors can Comment</div>\r\n                                ");


            
            #line 232 "..\..\Views\Productions\Details.cshtml"
                           Write(Html.ControlsWrapperEndTag());

            
            #line default
            #line hidden
WriteLiteral("                               \r\n                            </div>\r\n            " +
"                ");


            
            #line 234 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.FormButtons("Update"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </fieldset>\r\n                        </form>\r\n         " +
"           </div>\r\n");


            
            #line 238 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 239 "..\..\Views\Productions\Details.cshtml"
                 if (Model.IsMember)
                {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<div class=\"well\">\r\n\t\t\t\t\t\t<h3>Leave this Production</h3>\r\n\t\t\t\t\t\t<p>Leaving t" +
"his production will remove you as a member.  You can always rejoin later.</p>\r\n " +
"                       <form method=\"post\" action=\"");


            
            #line 244 "..\..\Views\Productions\Details.cshtml"
                                               Write(Url.Action("DeleteCurrent", "ProductionMembers"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            ");


            
            #line 245 "..\..\Views\Productions\Details.cshtml"
                       Write(Html.Hidden("projectId", Model.Data.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <input type=\"submit\" value=\"Resign from Production\"" +
" class=\"btn btn-danger\"/>\r\n                        </form>\r\n\t\t\t\t\t</div>         " +
"          \r\n");


            
            #line 249 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden

            
            #line 250 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanDelete)
                {                   

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<div class=\"");


            
            #line 252 "..\..\Views\Productions\Details.cshtml"
            Write(Html.AlertErrorClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t<h3>");


            
            #line 253 "..\..\Views\Productions\Details.cshtml"
      Write("Delete this Production");

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\t\t\t\t\t\t<p>");


            
            #line 254 "..\..\Views\Productions\Details.cshtml"
     Write("Are you 100% sure? This will delete EVERYTHING in this production. There is no undo.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                        <div class=\"alert-actions\">\r\n                      " +
"  <form method=\"post\" action=\"");


            
            #line 256 "..\..\Views\Productions\Details.cshtml"
                                               Write(Url.Action("Delete", "Productions"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <input type=\"submit\" value=\"");


            
            #line 257 "..\..\Views\Productions\Details.cshtml"
                                                    Write("Delete this Production");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-danger\"/>\r\n                        </form>\r\n                    " +
"    </div>\r\n\t\t\t\t\t</div>\r\n");


            
            #line 261 "..\..\Views\Productions\Details.cshtml"
                
                    
                }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <div id=\"video-details-container\" class=\"tabPane\">\r\n        <div " +
"id=\"player-container\"></div>\r\n        <div id=\"commentsArea\">\r\n            <h2>C" +
"omments <span class=\"quantity\" id=\"commentsQuantity\">(0)</span>\r\n");


            
            #line 269 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddComment)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"#\" class=\"");


            
            #line 271 "..\..\Views\Productions\Details.cshtml"
                                  Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" id=\"addCommentBtnInHeader\">Add Comment</a>\r\n");


            
            #line 272 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </h2>\r\n");


            
            #line 274 "..\..\Views\Productions\Details.cshtml"
             if (Model.Data.CanAddComment)
            {

            
            #line default
            #line hidden
WriteLiteral("                <form id=\"comment-add-form\" action=\"");


            
            #line 276 "..\..\Views\Productions\Details.cshtml"
                                               Write(Url.Action("Create", "Comments"));

            
            #line default
            #line hidden
WriteLiteral(@""" style=""display: none"">
                    <label for=""comment-add-form-body-input"">New Comment</label>
                    <textarea rows=""3"" class=""xxlarge"" id=""comment-add-form-body-input"" name=""body""></textarea>
                    <div id=""comment-add-form-isTimed-container"">
                        <label for=""comment-add-form-isTimed-group"">For</label>
                        <div id=""comment-add-form-isTimed-group"">                
                            <input type=""radio"" id=""comment-add-form-isTimed-input-true"" name=""timed"" value=""true"" />
                            <label for=""comment-add-form-isTimed-input-true"">Right Now (<span id=""comment-add-form-isTimed-timecode"">0:00</span>)</label>
                            <input type=""radio"" id=""comment-add-form-isTimed-input-false"" name=""timed"" value=""false"" />
                            <label for=""comment-add-form-isTimed-input-false"">Entire Video</label>
                        </div>
                    </div>
");


            
            #line 288 "..\..\Views\Productions\Details.cshtml"
                     if (!Model.Data.IsMember && !Model.SemiAnonymousUserName.HasChars())
                    {

            
            #line default
            #line hidden
WriteLiteral(@"                    <div class=""field"" id=""comment-add-form-name"">
                        <label for=""comment-add-form-name-input"">Your Name</label>
                        <input type=""text"" id=""comment-add-form-name-input"" name=""name"" value="""" />
                    </div>
");


            
            #line 294 "..\..\Views\Productions\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"buttons\">\r\n                        <input type=\"s" +
"ubmit\" value=\"Add Comment\" class=\"");


            
            #line 296 "..\..\Views\Productions\Details.cshtml"
                                                                   Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        <a href=\"#\" class=\"btn cancel-button\">Cancel</a>\r\n " +
"                   </div>\r\n                </form>\r\n");


            
            #line 300 "..\..\Views\Productions\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"commentsEmpty\" class=\"empty-data-msg ");


            
            #line 301 "..\..\Views\Productions\Details.cshtml"
                                                     Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 302 "..\..\Views\Productions\Details.cshtml"
            Write("No comments have been written yet.");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 303 "..\..\Views\Productions\Details.cshtml"
                 if (Model.Data.CanAddComment)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"#\">Be the first!</a>\r\n");


            
            #line 306 "..\..\Views\Productions\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div id=\"comments\">\r\n            </div>\r\n        " +
"</div>\r\n    </div>\r\n\r\n</div>\r\n<div id=\"sideBar\" class=\"span4\">    \r\n\r\n    <div i" +
"d=\"activity-container\">\r\n        <h4>");


            
            #line 317 "..\..\Views\Productions\Details.cshtml"
        Write("Latest Activity");

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n        <ul>\r\n        </ul>\r\n        <div id=\"activityEmpty\" class=\"empty-" +
"data-msg ");


            
            #line 320 "..\..\Views\Productions\Details.cshtml"
                                                 Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 321 "..\..\Views\Productions\Details.cshtml"
        Write("There's no recent activity.");

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n</div>");


        }
    }
}
#pragma warning restore 1591
