#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.AccountPlan
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AccountPlan/Edit-DowngradeInvalid.cshtml")]
    public class Edit_DowngradeInvalid : System.Web.Mvc.WebViewPage<AccountPlan_Edit_DowngradeInvalid>
    {
        public Edit_DowngradeInvalid()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\AccountPlan\Edit-DowngradeInvalid.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    
    ViewData["Heading"] = "Account Plan";


            
            #line default
            #line hidden
WriteLiteral("<div class=\"");


            
            #line 7 "..\..\Views\AccountPlan\Edit-DowngradeInvalid.cshtml"
       Write(Html.AlertErrorClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\nSorry but you can\'t downgrade to this plan because you have exceeded its limi" +
"t for <strong>");


            
            #line 8 "..\..\Views\AccountPlan\Edit-DowngradeInvalid.cshtml"
                                                                                      Write(Model.LimitsExceeded.Select(c => c.ToLowerInvariant()).ToArray().AssembleList());

            
            #line default
            #line hidden
WriteLiteral("</strong>.  Please delete the necessary stuff and you\'ll be able to downgrade.\r\n<" +
"/div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
