#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.MembershipRequests
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MembershipRequests/Created.cshtml")]
    public class Created : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Created()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\MembershipRequests\Created.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml"; 
    ViewData["PageTitle"] = "Request Sent";
    ViewData.AddBodyCss("membership-request-created");//had to do this because two different controllers use this view currently (productions and membershiprequests)       


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 9 "..\..\Views\MembershipRequests\Created.cshtml"
    Write("Request Sent");

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n<p class=\"");


            
            #line 11 "..\..\Views\MembershipRequests\Created.cshtml"
     Write(Html.AlertSuccessClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 12 "..\..\Views\MembershipRequests\Created.cshtml"
Write("We emailed the person in charge of the production.  You'll get an email once they decide. If you don't hear back in a while, check your junk mail. Then maybe contact them personally and ask them to add you as a team member.");

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
