#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Invoices
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Invoices/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<Invoices_Invoice>
    {
        public Details()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Invoices\Details.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    
    ViewData["Heading"] = "Invoice #{0} - {1}".FormatString(Model.Id, Model.Date.ToString(DateTimeFormat.ShortDate));


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


            
            #line 9 "..\..\Views\Invoices\Details.cshtml"
 if (Model.LineItems.HasItems())
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>");


            
            #line 11 "..\..\Views\Invoices\Details.cshtml"
    Write("Charges");

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");



WriteLiteral("    <table class=\"table table-striped\">\r\n        <thead>\r\n            <tr>\r\n     " +
"           <th>\r\n                    ");


            
            #line 16 "..\..\Views\Invoices\Details.cshtml"
                Write("Description");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");


            
            #line 19 "..\..\Views\Invoices\Details.cshtml"
                Write("Date");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");


            
            #line 22 "..\..\Views\Invoices\Details.cshtml"
                Write("Total");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n");


            
            #line 27 "..\..\Views\Invoices\Details.cshtml"
             foreach (var lineItem in Model.LineItems)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 30 "..\..\Views\Invoices\Details.cshtml"
                   Write(lineItem.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>");


            
            #line 32 "..\..\Views\Invoices\Details.cshtml"
                    Write(lineItem.StartDate.HasValue ? lineItem.StartDate.Value.ToString(DateTimeFormat.ShortDate) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>");


            
            #line 34 "..\..\Views\Invoices\Details.cshtml"
                   Write(lineItem.Amount.ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");


            
            #line 37 "..\..\Views\Invoices\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 40 "..\..\Views\Invoices\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 42 "..\..\Views\Invoices\Details.cshtml"
 if (Model.Payments.HasItems())
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>");


            
            #line 44 "..\..\Views\Invoices\Details.cshtml"
    Write("Payments");

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");



WriteLiteral("    <table class=\"table table-striped\">\r\n        <thead>\r\n            <tr>\r\n     " +
"           <th>\r\n                    ");


            
            #line 49 "..\..\Views\Invoices\Details.cshtml"
                Write("Date");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");


            
            #line 52 "..\..\Views\Invoices\Details.cshtml"
                Write("Description");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n                    ");


            
            #line 55 "..\..\Views\Invoices\Details.cshtml"
                Write("Total");

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n");


            
            #line 60 "..\..\Views\Invoices\Details.cshtml"
             foreach (var payment in Model.Payments)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 63 "..\..\Views\Invoices\Details.cshtml"
                   Write(payment.Date.ToString(DateTimeFormat.ShortDate));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 64 "..\..\Views\Invoices\Details.cshtml"
                   Write(payment.Message.CharsOr("Thanks!"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 65 "..\..\Views\Invoices\Details.cshtml"
                   Write(payment.Amount.ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");


            
            #line 67 "..\..\Views\Invoices\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 70 "..\..\Views\Invoices\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>");


            
            #line 72 "..\..\Views\Invoices\Details.cshtml"
Write("Bottom Line");

            
            #line default
            #line hidden
WriteLiteral("</h3>    \r\n<ul>\r\n<li>\r\n");


            
            #line 75 "..\..\Views\Invoices\Details.cshtml"
Write("Subtotal:");

            
            #line default
            #line hidden
WriteLiteral(" <strong>");


            
            #line 75 "..\..\Views\Invoices\Details.cshtml"
                  Write(Model.Subtotal.ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n</li>\r\n<li>\r\n");


            
            #line 78 "..\..\Views\Invoices\Details.cshtml"
Write("Paid:");

            
            #line default
            #line hidden
WriteLiteral(" <strong>");


            
            #line 78 "..\..\Views\Invoices\Details.cshtml"
              Write(Model.Paid.ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n</li>\r\n<li>\r\n");


            
            #line 81 "..\..\Views\Invoices\Details.cshtml"
Write("Total Due:");

            
            #line default
            #line hidden
WriteLiteral(" <strong>");


            
            #line 81 "..\..\Views\Invoices\Details.cshtml"
                   Write(Model.TotalDue.ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n</li>\r\n\r\n</ul>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
