#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Dashboard
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Dashboard/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Dashboard_Index>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Dashboard\Index.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Medium.cshtml";
    
    ViewData["PageTitle"] = S.Dashboard_Title;
    var account = Model.Account;    
    AccountStatus? accountStatus = account == null ? new AccountStatus?() : account.Status;
    Takeoff.Data.IPlan plan = account.MapIfNotNull(a => a.Plan);
    ViewData["pageCssClass"] = @"dashboard-index";


            
            #line default
            #line hidden

DefineSection("JsExternal", () => {

WriteLiteral("\r\n    ");


            
            #line 13 "..\..\Views\Dashboard\Index.cshtml"
Write(Html.JsLib("interior.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 14 "..\..\Views\Dashboard\Index.cshtml"
Write(Html.JsLib("app-dashboard.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.Dashboard(");


            
            #line 18 "..\..\Views\Dashboard\Index.cshtml"
                      Write(Html.Json(new
      {
          Activity = Model.Activity,
          Productions = Model.Productions,
      }));

            
            #line default
            #line hidden
WriteLiteral(");\r\n\r\n");


});

WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 27 "..\..\Views\Dashboard\Index.cshtml"
   Write(S.Dashboard_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 30 "..\..\Views\Dashboard\Index.cshtml"
 if (accountStatus.HasValue && accountStatus.Value == AccountStatus.Trial)
{

            
            #line default
            #line hidden
WriteLiteral("    <div id=\"accountStatus\" class=\"");


            
            #line 32 "..\..\Views\Dashboard\Index.cshtml"
                              Write(Html.AlertWarningClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 33 "..\..\Views\Dashboard\Index.cshtml"
   Write(S.Dashboard_PlanUsage_DaysLeft.FormatResource(Math.Max(0, account.DaysLeftInTrial.GetValueOrDefault()), Html.StartActionLink("Subscribe", "Signup", new { returnUrl = Url.Action("dashboard") })));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 35 "..\..\Views\Dashboard\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<section id=\"productions\">\r\n<h2>");


            
            #line 38 "..\..\Views\Dashboard\Index.cshtml"
Write(S.Dashboard_Productions_Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n<a class=\"btn\" href=\"");


            
            #line 39 "..\..\Views\Dashboard\Index.cshtml"
                Write(Url.Action("Create", "Productions"));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 39 "..\..\Views\Dashboard\Index.cshtml"
                                                      Write(S.Dashboard_NewProduction_Text);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
</h2>
<table id=""productions-data"" cellspacing=""0"" class=""data table table-striped"">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Date Created
            </th>
            <th>
                Latest Change
            </th>
            <th>
                Created By
            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div class=""empty-data-msg ");


            
            #line 61 "..\..\Views\Dashboard\Index.cshtml"
                      Write(Html.AlertInfoClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    ");


            
            #line 62 "..\..\Views\Dashboard\Index.cshtml"
Write(S.Dashboard_NoProductions.FormatResource(Html.StartActionLink("Create", "Productions")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n</section>\r\n\r\n\r\n");


            
            #line 67 "..\..\Views\Dashboard\Index.cshtml"
 if (Model.MembershipRequests.HasItems())
{   

            
            #line default
            #line hidden
WriteLiteral("<section id=\"membership-requests\">    \r\n<h2>Membership Requests</h2>\r\n<ul>\r\n");


            
            #line 72 "..\..\Views\Dashboard\Index.cshtml"
     foreach (var request in Model.MembershipRequests)
    {
        if (request.IsInvitation)
        {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            ");


            
            #line 77 "..\..\Views\Dashboard\Index.cshtml"
       Write(request.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            invited you to join &quot;");


            
            #line 78 "..\..\Views\Dashboard\Index.cshtml"
                                 Write(request.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("&quot;. [ <a href=\"");


            
            #line 78 "..\..\Views\Dashboard\Index.cshtml"
                                                                            Write(Url.ActionDetails("Productions", request.ProductionId));

            
            #line default
            #line hidden
WriteLiteral("\">Details</a> ]</li>\r\n");


            
            #line 79 "..\..\Views\Dashboard\Index.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            ");


            
            #line 83 "..\..\Views\Dashboard\Index.cshtml"
       Write(request.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            wants to join &quot;");


            
            #line 84 "..\..\Views\Dashboard\Index.cshtml"
                           Write(request.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("&quot;. [ <a href=\"");


            
            #line 84 "..\..\Views\Dashboard\Index.cshtml"
                                                                      Write(Url.ActionDetails("MembershipRequests", request.Id));

            
            #line default
            #line hidden
WriteLiteral("\">Details</a> ]</li>\r\n");


            
            #line 85 "..\..\Views\Dashboard\Index.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n</section>\r\n");


            
            #line 89 "..\..\Views\Dashboard\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<section id=\"activity\">\r\n<h2>");


            
            #line 91 "..\..\Views\Dashboard\Index.cshtml"
Write(S.Dashboard_Activity_Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<ul>\r\n</ul>\r\n<div class=\"empty-data-msg ");


            
            #line 94 "..\..\Views\Dashboard\Index.cshtml"
                      Write(Html.AlertInfoClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    ");


            
            #line 95 "..\..\Views\Dashboard\Index.cshtml"
Write(S.Dashboard_Activity_EmptyMsg);

            
            #line default
            #line hidden
WriteLiteral("\r\n </divclass>\r\n</section>\r\n");


        }
    }
}
#pragma warning restore 1591
