#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Root
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Root/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Root\Index.cshtml"
  
    Layout = "~/Views/Shared/Layout-External-Medium.cshtml";

    ViewData["PageTitle"] = S.Home_PageTitle;

    var options = new
    {
        message = (string)ViewData["message"],
        videoPlayerUrl = this.Url.Asset("Assets/ExternalPlayer.swf"),
    };



            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.home(");


            
            #line 15 "..\..\Views\Root\Index.cshtml"
                 Write(Html.Json(options));

            
            #line default
            #line hidden
WriteLiteral(");\r\n");


});

WriteLiteral("\r\n<div class=\"hero-unit\">\r\n    <h1>");


            
            #line 18 "..\..\Views\Root\Index.cshtml"
    Write("Simple Video Review & Approval");

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    <p>");


            
            #line 19 "..\..\Views\Root\Index.cshtml"
   Write("Still using email, ftp, YouTube, or Vimeo to collaborate during post production?  Then you'll love Takeoff.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    <form method=\"post\" action=\"");


            
            #line 20 "..\..\Views\Root\Index.cshtml"
                           Write(Url.Action("Create", "Signup", new { type = SignupType.StartTrial }, UrlType.RelativeHttps));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <input class=\"btn btn-large btn-primary\" value=\"");


            
            #line 21 "..\..\Views\Root\Index.cshtml"
                                                Write("Try Instantly");

            
            #line default
            #line hidden
WriteLiteral("\" type=\"submit\" />\r\n    <span>");


            
            #line 22 "..\..\Views\Root\Index.cshtml"
      Write("No Personal Info Required!");

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </form>\r\n</div>\r\n<section>\r\n<div class=\"page-header\">\r\n        <h1>");


            
            #line 27 "..\..\Views\Root\Index.cshtml"
        Write("Highlights");

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n      </div>\r\n<ul class=\"thumbnails\">\r\n    <li class=\"span3\">\r\n        <di" +
"v class=\"thumbnail\">\r\n            <img alt=\"");


            
            #line 32 "..\..\Views\Root\Index.cshtml"
                  Write("Comment Screenshot");

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 32 "..\..\Views\Root\Index.cshtml"
                                               Write(this.Url.Asset("/Assets/img/home-highlight-1.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <div class=\"caption\">\r\n                <h5>");


            
            #line 34 "..\..\Views\Root\Index.cshtml"
                Write("Video Feedback");

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <p>");


            
            #line 35 "..\..\Views\Root\Index.cshtml"
               Write("Write comments with frame-by-frame precision.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </li>\r\n    <li class=\"span3\">\r\n    " +
"    <div class=\"thumbnail\">\r\n            <img alt=\"");


            
            #line 41 "..\..\Views\Root\Index.cshtml"
                  Write("Activity Screenshot");

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 41 "..\..\Views\Root\Index.cshtml"
                                                Write(this.Url.Asset("/Assets/img/home-highlight-2.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <div class=\"caption\">\r\n                <h5>");


            
            #line 43 "..\..\Views\Root\Index.cshtml"
                Write("Privacy");

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <p>");


            
            #line 44 "..\..\Views\Root\Index.cshtml"
               Write("Only people you invite ever have access to your videos.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </li>\r\n    <li class=\"span3\">\r\n    " +
"    <div class=\"thumbnail\">\r\n            <img alt=\"");


            
            #line 50 "..\..\Views\Root\Index.cshtml"
                  Write("Assets Screenshot");

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 50 "..\..\Views\Root\Index.cshtml"
                                              Write(this.Url.Asset("/Assets/img/home-highlight-3.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <div class=\"caption\">\r\n                <h5>");


            
            #line 52 "..\..\Views\Root\Index.cshtml"
                Write("File Sharing");

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <p>");


            
            #line 53 "..\..\Views\Root\Index.cshtml"
               Write("Share files like scripts and soundtracks with teammates.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </li>\r\n    <li class=\"span3\">\r\n    " +
"    <div class=\"thumbnail\">\r\n            <img alt=\"");


            
            #line 59 "..\..\Views\Root\Index.cshtml"
                  Write("Mobile Screenshot");

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 59 "..\..\Views\Root\Index.cshtml"
                                              Write(this.Url.Asset("/Assets/img/home-highlight-4.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <div class=\"caption\">\r\n                <h5>");


            
            #line 61 "..\..\Views\Root\Index.cshtml"
                Write("Everywhere");

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n                <p>");


            
            #line 62 "..\..\Views\Root\Index.cshtml"
               Write("Takeoff works on the web and mobile devices.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </li>\r\n</ul>\r\n</section>\r\n<section " +
"id=\"quotes-container\">\r\n    <div class=\"page-header\">\r\n        <h1>");


            
            #line 70 "..\..\Views\Root\Index.cshtml"
        Write("What They're Saying");

            
            #line default
            #line hidden
WriteLiteral(@"</h1>
      </div>
    <ul id=""quotes"" class=""unstyled"">
        <li><blockquote><p>Takeoff saves me time, heartache, and makes me look better for my clients.</p><small>Adam Kaplan - ASK Media Productions</small></blockquote></li>
        <li><blockquote><p>It is everything I need in a video collaboration tool.</p><small>Michael Hanrahan - President, The Ocean Channel</small></blockquote></li>
        <li><blockquote><p>It's so easy...there's really nothing to learn. It just works.</p><small>Eric Rodriguez - Videographer</small></blockquote></li>
        <li><blockquote><p>After Takeoff, things went from frustrating to pleasant.</p><small>Harry Dollard - InTime Solutions</small></blockquote></li>
        <li><blockquote><p>We don't have to ship tapes or transfer huge video files!</p><small>Joel Connable - Travel TV News</small></blockquote></li>
        <li><blockquote><p>What a great weapon in my arsenal. It's so easy and so worth it.</p><small>Jeff Barnes - Final Cutz</small></blockquote></li>
    </ul>
</section>
<section id=""comparison"">
     <div class=""page-header"">
        <h1>");


            
            #line 83 "..\..\Views\Root\Index.cshtml"
       Write(S.Home_ComparisonSection_Heading);

            
            #line default
            #line hidden
WriteLiteral(@"</h1>
     </div>
    <ul class=""nav nav-tabs"">
        <li class=""active""><a href=""#takeoff-vs-email"" data-toggle=""tab"">Email</a></li>
        <li><a href=""#takeoff-vs-youtube"" data-toggle=""tab"">YouTube</a></li>
        <li><a href=""#takeoff-vs-ftp"" data-toggle=""tab"">FTP</a></li>
        <li><a href=""#takeoff-vs-finalcutserver"" data-toggle=""tab"">Final Cut Server</a></li>
    </ul>
    <div class=""tab-content"">
        <table class=""tab-pane active table table-striped"" id=""takeoff-vs-email"">
            <thead>
                <tr>
                    <th></th>
                    <th>Takeoff</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Send large files</td>
                    <td><img src=""");


            
            #line 103 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 104 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\t\r\n               " +
"     <td>Avoid transferring video files just to watch</td>\r\n                    " +
"<td><img src=\"");


            
            #line 108 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 109 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Know everyone can watch your videos</td>\r\n                    <td><img s" +
"rc=\"");


            
            #line 113 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 114 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Easily write comments for specific moments</td>\r\n                    <" +
"td><img src=\"");


            
            #line 118 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n\r\n                    <td><img src=\"");


            
            #line 120 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Keep all files in a single organized place</td>\r\n                    <" +
"td><img src=\"");


            
            #line 124 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 125 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Know what video is the latest</td>\r\n\r\n                    <td><img src=\"" +
"");


            
            #line 130 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 131 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""No"" /></td>
                </tr>                
            </tbody>
            <tfoot>
                <tr>
                    <th colspan=""3"">Bottom line: Takeoff never stops you from using email.  But it works much better than email for many aspects of video production.</th>
                </tr>
            </tfoot>
        </table>
        <table class=""tab-pane table table-striped"" id=""takeoff-vs-youtube"">
            <thead>
                <tr>
                    <th></th>
                    <th>Takeoff</th>

                    <th>YouTube</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Limit video duration</td>
                    <td><img src=""");


            
            #line 152 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 153 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Ad free</td>\r\n                    <td><img src=\"");


            
            #line 157 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 158 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Easily write comments for specific moments</td>\r\n                    <" +
"td><img src=\"");


            
            #line 162 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n\r\n                    <td><img src=\"");


            
            #line 164 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Keep all asset files in a single organized place</td>\r\n               " +
"     <td><img src=\"");


            
            #line 168 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 169 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Permit downloading of videos</td>\r\n                    <td><img src=\"");


            
            #line 173 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 174 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Private by nature</td>\r\n                    <td><img src=\"");


            
            #line 178 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 179 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Add videos without sending out new links</td>\r\n                    <td><" +
"img src=\"");


            
            #line 183 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 184 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""No"" /></td>
                </tr>

            </tbody>
            <tfoot>
                <tr>
                    <th colspan=""3"">Bottom line:  YouTube (and similar sites) was built to show video once it's completed, not while it's still being produced.  Takeoff was built from the ground up to be used during production, so it has many crucial features YouTube lacks.  Use YouTube...just use it after Takeoff :)</th>
                </tr>
            </tfoot>
        </table>
        <table  class=""tab-pane table table-striped"" id=""takeoff-vs-ftp"">
            <thead>
                <tr>
                    <th></th>
                    <th>Takeoff</th>

                    <th>FTP</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Know everyone can watch your videos</td>
                    <td><img src=""");


            
            #line 206 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 207 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\t\r\n               " +
"     <td>Easily write comments for specific moments</td>\r\n                    <t" +
"d><img src=\"");


            
            #line 211 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 212 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Keep communication in a centralized place</td>\r\n                    <t" +
"d><img src=\"");


            
            #line 216 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 217 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\t\r\n               " +
"     <td>Avoid transferring video files just to watch</td>\r\n                    " +
"<td><img src=\"");


            
            #line 221 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 222 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>                \t\r\n                <tr>\t" +
"\r\n                    <td>Easily write comments for specific moments</td>\r\n     " +
"               <td><img src=\"");


            
            #line 226 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 227 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\r\n               " +
"     <td>Automatic file management</td>\r\n                    <td><img src=\"");


            
            #line 231 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 232 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>No special programs needed</td>\r\n                    <td><img src=\"");


            
            #line 236 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 237 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""No"" /></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan=""3"">Bottom line:  FTP lets you share large files but it's a huge hassle.  Takeoff eliminates all the problems that FTP presents.  Good riddance!</th>
                </tr>
            </tfoot>
        </table>
        <table class=""tab-pane table table-striped"" id=""takeoff-vs-finalcutserver"">
            <thead>
                <tr>
                    <th></th>
                    <th>Takeoff</th>

                    <th>FCP Server</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Affordable for anyone</td>
                    <td><img src=""");


            
            #line 258 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 259 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Nothing to install</td>\r\n                    <td><img src=\"");


            
            #line 263 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 264 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\t\r\n              " +
"      <td>Doesn\'t require a Mac</td>\r\n                    <td><img src=\"");


            
            #line 268 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 269 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\t\r\n               " +
"     <td>Easily write comments for specific moments</td>\r\n                    <t" +
"d><img src=\"");


            
            #line 273 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 274 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\t\r\n                <tr>\r\n               " +
"     <td>Visual customizations</td>\r\n                    <td><img src=\"");


            
            #line 278 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 279 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"No\" /></td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>Works with any editing program</td>\r\n                    <td><img src=\"");


            
            #line 283 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-check.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Yes\" /></td>\r\n                    <td><img src=\"");


            
            #line 284 "..\..\Views\Root\Index.cshtml"
                             Write(this.Url.Asset("/Assets/img/icon-cross.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""No"" /></td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th colspan=""3"">Bottom line:  Final Cut Server was built for larger production houses and is overkill for most of us.  Takeoff is simple, inexpensive, and easy to learn.</th>
                </tr>
            </tfoot>
        </table>
    </div>
</section>
");


        }
    }
}
#pragma warning restore 1591
