#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Root
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Root/Privacy.cshtml")]
    public class Privacy : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Privacy()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Root\Privacy.cshtml"
  
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
    ViewData["PageTitle"] = "Takeoff's Privacy Policy";


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>Takeoff\'s Privacy Policy</h1>\r\n");


});

WriteLiteral("\r\n\r\n<p>This Privacy Policy was last modified on November 14, 2011.\r\nTakeoff, Inc." +
" (\"Takeoff,\" \"we,\" or \"us\") knows that you care how information about you is use" +
"d and shared. This Privacy Policy explains what information of yours will be col" +
"lected by Takeoff when you use Takeoff.com and related services (the \"Service\")," +
" how the information will be used, and how you can control the collection, corre" +
"ction and/or deletion of information. We will not use or share your information " +
"with anyone except as described in this Privacy Policy.\r\n</p>\r\n\r\n<h2>Information" +
" We Collect</h2>\r\n\r\n<h3>User-Provided Information</h3>\r\n<p>You are required to p" +
"rovide us information about yourself, such as your name, email address, and a pa" +
"ssword which is used to protect your account from unauthorized access, when you " +
"register with the Service. If you correspond with us by email, we may retain the" +
" content of your email messages, your email address and our responses. If you in" +
"vite another party to the Service, we may retain that party\'s email address. By " +
"using or accessing our Services, you are accepting the practices of this Privacy" +
" Policy.</p>\r\n<p>Your Production (as defined in the Terms of Use) becomes availa" +
"ble to Collaborators in your Production Group (as those terms are defined in the" +
" Terms of Use). Any personal information you post to the Service becomes availab" +
"le to other Users with whom you choose to communicate.</p>\r\n<p>You post User Con" +
"tent (as defined in the Takeoff Terms of Use) using the Service at your own risk" +
". Although we employ commercially reasonable technical and organizational measur" +
"es designed to secure your personal information from improper use, please be awa" +
"re that no security measures are perfect or impenetrable. We cannot control the " +
"actions of other users with whom you may choose to share your User Content. Ther" +
"efore, we cannot and do not guarantee that unauthorized third parties will never" +
" be able to view the User Content you post using. We are not responsible for cir" +
"cumvention of any privacy settings or security measures contained on the Service" +
". You acknowledge that, even after removal, copies of User Content may remain vi" +
"ewable in cached and archived pages or if other Users or Collaborators have copi" +
"ed or stored your User Content.</p>\r\n\r\n<h3>Cookies Information</h3>\r\n<p>When you" +
" visit Takeoffvideo.com, we may send one or more cookies - a small text file con" +
"taining a string of alphanumeric characters - to your computer that uniquely ide" +
"ntifies your browser and lets Takeoff help you log in faster and enhance your na" +
"vigation through the site. A cookie does not collect personal information about " +
"you. Takeoff uses both session cookies and persistent cookies. A persistent cook" +
"ie remains on your hard drive after you close your browser. Persistent cookies m" +
"ay be used by your browser on subsequent visits to the site. Persistent cookies " +
"can be removed by following your web browser\'s directions. A session cookie is t" +
"emporary and disappears after you close your browser. You can reset your web bro" +
"wser to refuse all cookies or to indicate when a cookie is being sent. However, " +
"some features of the Service may not function properly if the ability to accept " +
"cookies is disabled.</p>\r\n\r\n<h3>Log File Information</h3>\r\n<p>Log file informati" +
"on is automatically reported by your browser each time you access a web page. Wh" +
"en you register with or view our site, our servers automatically record certain " +
"information that your web browser sends whenever you visit any website. These se" +
"rver logs may include information such as your web request, Internet Protocol (\"" +
"IP\") address, browser type, referring / exit pages and URLs, number of clicks, d" +
"omain names, landing pages, pages viewed, and other such information.</p>\r\n\r\n<h3" +
">Clear Gifs Information</h3>\r\n<p>When you use the Service, we may employ clear g" +
"ifs (a.k.a. Web Beacons) which are used to track the online usage patterns of ou" +
"r users anonymously. No personally identifiable information from your Takeoff ac" +
"count is collected using these clear gifs. In addition, we may also use clear gi" +
"fs in HTML-based emails sent to our users to track which emails are opened by re" +
"cipients. The information is used to enable more accurate reporting, improve the" +
" effectiveness of our marketing, and make Takeoff better for our users.</p>\r\n\r\n<" +
"h2>How We Use Your Information</h2>\r\n\r\n<p>We use the personal information you su" +
"bmit to operate, maintain, and provide to you the features and functionality of " +
"the Service.</p>\r\n<p>Any personal information or content that you voluntarily di" +
"sclose for posting to the Service for your Production Group (for instance, in Us" +
"er Content you post) becomes available to Collaborators in the Production Group." +
"</p>\r\n<p>If you remove User Content, copies may remain viewable in cached and ar" +
"chived pages or if other users have copied or stored your User Content.</p>\r\n<p>" +
"By providing Takeoff with your email address, you consent to our using the email" +
" address to send you Service-related notices, including any notices required by " +
"law, in lieu of communication by postal mail. You may not opt out of Service-rel" +
"ated e-mails. We may also use your email address to send you other messages, suc" +
"h as newsletters, changes to features of the Service, or special offers. If you " +
"do not want to receive such email messages, you may opt out by sending an email " +
"message to support@Takeoffvideo.com with the word \"No email\" in the subject fiel" +
"d. Opting out may prevent you from receiving email messages regarding updates, i" +
"mprovements, or offers.</p>\r\n<p>Takeoff may use certain information about you an" +
"d/or your User Content without identifying you as an individual to third parties" +
". We do this for purposes such as analyzing and tracking how the Service is used" +
", diagnosing service or technical problems, maintaining security, and personaliz" +
"ing advertisements and promotions.</p>\r\n<p>Takeoff reserves the right, but has n" +
"o obligation, to monitor the User Content you post on the site. Takeoff has the " +
"right to remove any such information or material for any reason or no reason, in" +
"cluding without limitation if, in its sole opinion, such information or material" +
" violates, or may violate, any applicable law or our Terms of Use Agreement or t" +
"o protect or defend its rights or property or those of any third party. Takeoff " +
"also reserves the right to remove information upon the request of any third part" +
"y.</p>\r\n<p>We use cookies, clear gifs, and log file information to: (a) remember" +
" information so that you will not have to re-enter it during your visit or the n" +
"ext time you visit the site; (b) provide custom, personalized content and inform" +
"ation; (c) monitor the effectiveness of our service; (d) monitor aggregate metri" +
"cs such as total number of visitors and traffic; (e) diagnose or fix technology " +
"problems reported by our users or engineers that are associated with the IP addr" +
"esses controlled by a specific web company or ISP; and (f) help you efficiently " +
"access your information after you sign in.</p>\r\n\r\n<h2>How We Share Your Informat" +
"ion</h2>\r\n\r\n<h3>Personally Identifiable Information</h3>\r\n<p>Except as expressly" +
" provided in this Privacy Policy, Takeoff will not rent or sell your personally " +
"identifiable information to others. Takeoff may share your personally identifiab" +
"le information with third parties for the purpose of providing services to you o" +
"r suggesting beneficial third party services that may be of interest to you. We " +
"may store personal information in locations outside the direct control of Takeof" +
"f (for instance, on servers or databases co-located with hosting providers).</p>" +
"\r\n<p>As we develop our business, we may buy or sell assets or business offerings" +
". Customer, email, and visitor information is generally one of the transferred b" +
"usiness assets in these types of transactions. We may also transfer such informa" +
"tion in the course of corporate divestitures, mergers, or dissolution.</p>\r\n<p>E" +
"xcept as otherwise described in this privacy statement, Takeoff will not disclos" +
"e personal information or your User Content to any third party unless required t" +
"o do so by law or subpoena or if we believe that such action is necessary to (a)" +
" conform to the law, comply with legal process served on us or our affiliates, o" +
"r investigate, prevent, or take action regarding suspected or actual illegal act" +
"ivities; (b) to enforce our Terms of Use, take precautions against liability, to" +
" investigate and defend ourselves against any third-party claims or allegations," +
" to assist government enforcement agencies, or to protect the security or integr" +
"ity of our site; and (c) to exercise or protect the rights, property, or persona" +
"l safety of Takeoff, our users or others.</p>\r\n\r\n<h3>Non-Personally Identifiable" +
" Information</h3>\r\n<p>We may share non-personally identifiable information (such" +
" as anonymous usage data, referring/exit pages and URLs, platform types, number " +
"of clicks, etc.) with interested third parties to help them understand the usage" +
" patterns for certain Takeoff services.</p>\r\n<p>Takeoff may allow other companie" +
"s, called third-party ad servers or ad networks, to serve advertisements on the " +
"Takeoff site. These third-party ad servers or ad networks use technology to send" +
", directly to your browser, the advertisements and links that appear on Takeoff." +
" They automatically receive your IP address when this happens. They may also use" +
" other technologies (such as cookies, JavaScript, or Web Beacons) to measure the" +
" effectiveness of their advertisements and to personalize the advertising conten" +
"t. Takeoff does not have access to or control of these third-party advertiser\'s " +
"technologies.</p>\r\n<p>Takeoff does not provide any personally identifiable infor" +
"mation to these third-party ad servers or ad networks without your consent. Howe" +
"ver, please note that if an advertiser asks Takeoff to show an advertisement to " +
"a certain audience and you respond to that advertisement, the advertiser or ad-s" +
"erver may conclude that you fit the description of the audience they are trying " +
"to reach.</p>\r\n<p>You should consult the respective privacy policies of these th" +
"ird-party ad servers or ad networks. The Takeoff Privacy Policy does not apply t" +
"o, and we cannot control the activities of, such advertisers.</p>\r\n\r\n<h2>How We " +
"Protect Your Information</h2>\r\n<p>Takeoff uses commercially reasonable physical," +
" managerial, and technical safeguards to preserve the integrity and security of " +
"your personal information. We cannot, however, ensure or warrant the security of" +
" any information you transmit to Takeoff and you do so at your own risk. Once we" +
" receive your transmission of information, Takeoff makes commercially reasonable" +
" efforts to ensure the security of our and our licensors\' systems. However, plea" +
"se note that this is not a guarantee that such information may not be accessed, " +
"disclosed, altered, or destroyed by breach of any of our physical, technical, or" +
" managerial safeguards.</p>\r\n<p>To protect your privacy and security, we take re" +
"asonable steps (such as requesting a unique password) to verify your identity be" +
"fore granting you access to your account. You are responsible for maintaining th" +
"e secrecy of your unique password and account information, and for controlling a" +
"ccess to your email communications from Takeoff, at all times.</p>\r\n\r\n<h2>Compro" +
"mise of Personal Information</h2>\r\n<p>In the event that personal information is " +
"compromised as a result of a breach of security, Takeoff will promptly notify th" +
"ose persons whose personal information has been compromised, in accordance with " +
"the notification procedures set forth in this Privacy Policy, or as otherwise re" +
"quired by applicable law. You acknowledge that Takeoff is not liable in the even" +
"t that personal information is compromised.</p>\r\n\r\n<h2>Your Choices About Your I" +
"nformation</h2>\r\n<p>You may, of course, decline to submit personally identifiabl" +
"e information through Takeoff, in which case Takeoff may not be able to provide " +
"certain services to you. You may update or correct your account information and " +
"email preferences at any time by logging in to your account. You can review and " +
"correct the information about you that Takeoff keeps on file by contacting us di" +
"rectly at support@takeoffvideo.com.</p>\r\n\r\n<h2>Children\'s Privacy</h2>\r\n<p>Prote" +
"cting the privacy of young children is especially important. For that reason, Ta" +
"keoff does not knowingly collect or solicit personal information from anyone und" +
"er the age of 13 or knowingly allow such persons to register. If you are under 1" +
"3, please do not send any information about yourself to us, including your name," +
" address, telephone number, or email address. No one under age 13 is allowed to " +
"provide any personal information to Takeoff or on the Service. In the event that" +
" we learn that we have collected personal information from a child under age 13 " +
"without verification of parental consent, we will delete that information as qui" +
"ckly as possible. If you believe that we might have any information from or abou" +
"t a child under 13, please contact us at privacy@takeoffvideo.com.</p>\r\n\r\n<h2>Li" +
"nks to Other Web Sites</h2>\r\n<p>We are not responsible for the practices employe" +
"d by Web sites linked to or from our Web site nor the information or content con" +
"tained therein. Please remember that when you use a link to go from our Web site" +
" to another Web site, our Privacy Policy is no longer in effect. Your browsing a" +
"nd interaction on any other Web site, including those that have a link on our We" +
"b site, is subject to that Web site\'s own rules and policies. Please read over t" +
"hose rules and policies before proceeding.</p>\r\n\r\n<h2>Notification Procedures</h" +
"2>\r\n<p>It is our policy to provide notifications, whether such notifications are" +
" required by law or are for marketing or other business related purposes, to you" +
" via email notice, written or hard copy notice, or through conspicuous posting o" +
"f such notice on our website, as determined by Takeoff in its sole discretion. W" +
"e reserve the right to determine the form and means of providing notifications t" +
"o you, provided that you may opt out of certain means of notification as describ" +
"ed in this Privacy Policy.</p>\r\n<p>Your use of Takeoff\'s services, and any dispu" +
"tes arising from it, is subject to this Privacy Policy and Takeoff\'s Terms of Us" +
"e, including dispute resolution, arbitration, limitation on damages and choice o" +
"f law.</p>\r\n\r\n<h2>Changes to Our Privacy Policy</h2>\r\n<p>If we change our privac" +
"y policies and procedures, we will post those changes on our website to keep you" +
" aware of what information we collect, how we use it and under what circumstance" +
"s we may disclose it. Changes to this Privacy Policy are effective when they are" +
" posted on this page.</p>\r\n<p>If you have any questions about this Privacy Polic" +
"y, the practices of this site, or your dealings with this Web site, please conta" +
"ct us at privacy@takeoffvideo.com, or send mail to:<br/>\r\nTakeoff, Inc.<br/>\r\n21" +
"8 Denison Street, Unit 1<br/>\r\nHighland Park, NJ 08904\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
