#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Root
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Root/Try.cshtml")]
    public class Try : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Try()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Root\Try.cshtml"
  
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
    ViewData["PageTitle"] = "Try";


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    $(\"#mainForm\").madValidate({ useAjax: false }); \r\n    $(\"#timezoneOffset\")." +
"val(new Date().getTimezoneOffset());\r\n");


});

WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n\t<h1>");


            
            #line 13 "..\..\Views\Root\Try.cshtml"
Write(S.Trial_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n<p class=\"instructions\">\r\n    ");


            
            #line 16 "..\..\Views\Root\Try.cshtml"
Write("Want to try Takeoff {0}without giving any personal information{/0}?  Then hit the button below, see if Takeoff is right for you, and sign up if and when you want.".FormatResource(Html.Element("strong")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n<div class=\"actions\">\r\n            <form method=\"post\" action=\"");


            
            #line 20 "..\..\Views\Root\Try.cshtml"
                                   Write(Url.Action("Create", "Signup", new { type = SignupType.StartTrial }, UrlType.RelativeHttps));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <input class=\"btn btn-large btn-primary\" value=\"");


            
            #line 21 "..\..\Views\Root\Try.cshtml"
                                                            Write("Try Takeoff Now");

            
            #line default
            #line hidden
WriteLiteral("\" type=\"submit\" />\r\n            </form>    \r\n</div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
