#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Email
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/Layout-Announcement-Feature.cshtml")]
    public class Layout_Announcement_Feature : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout_Announcement_Feature()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Email\Layout-Announcement-Feature.cshtml"
  
    Layout = "~/Views/Email/Layout-Simple.cshtml";    
    var changeSettingsUrl = Url.Action<AccountNotificationsController>(c => c.Index(), UrlType.AbsoluteHttps);
    ViewData["ExplanationPlain"] = "You are receiving this email because you are set to receive announcments for new features.  To unsubscribe from these types of email, please visit:" + Environment.NewLine + changeSettingsUrl;
    this.RedefineSection("Subject");
    this.RedefineSection("Plain");
        


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("HtmlExplanation", () => {

WriteLiteral("\r\nYou are receiving this email because you are set to receive announcments for ne" +
"w features.  To unsubscribe from these types of email, please visit <a href=\"");


            
            #line 12 "..\..\Views\Email\Layout-Announcement-Feature.cshtml"
                                                                                                                                                       Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 12 "..\..\Views\Email\Layout-Announcement-Feature.cshtml"
                                                                                                                                                                           Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("</a> or email <a href=\"mailto:support@takeoffvideo.com\">support@takeoffvideo.com<" +
"/a> and we\'ll help you.\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 15 "..\..\Views\Email\Layout-Announcement-Feature.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
