#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Email
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/ProductionMember-Invited-NewUser.cshtml")]
    public class ProductionMember_Invited_NewUser : System.Web.Mvc.WebViewPage<Email_AddUserToProduction>
    {
        public ProductionMember_Invited_NewUser()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
  
    Layout = "~/Views/Email/Layout-ProductionBase.cshtml";


            
            #line default
            #line hidden

DefineSection("Subject", () => {

WriteLiteral("\r\nPlease Join ");


            
            #line 7 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
       Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlHeader", () => {

WriteLiteral("\r\n");


            
            #line 10 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
Write(Model.AddedByName);

            
            #line default
            #line hidden
WriteLiteral(" would like you to join ");


            
            #line 10 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                     Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlExplanation", () => {

WriteLiteral("\r\nYou are recieving this because ");


            
            #line 14 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                          Write(Model.AddedByName);

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 14 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                              Write(Model.AddedByEmail);

            
            #line default
            #line hidden
WriteLiteral(") invited you to collaborate on a production in Takeoff.  If you don\'t want to jo" +
"in, simply ignore this email.\r\n");


});

WriteLiteral("\r\n");


DefineSection("Plain", () => {

WriteLiteral("\r\n");


            
            #line 17 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
Write(Model.AddedByName);

            
            #line default
            #line hidden
WriteLiteral(" would like you to join ");


            
            #line 17 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                     Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral(" on Takeoff.  Takeoff is a web site that makes it easy to collaborate on video.  " +
"To view it, please go to the following link:\r\n");


            
            #line 18 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
Write(Html.Raw(Model.ProductionUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
 if (Model.Note.HasChars())
{
            
            #line default
            #line hidden
WriteLiteral("    \r\nHere\'s a note ");


            
            #line 21 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
         Write(Html.Raw(Model.AddedByName));

            
            #line default
            #line hidden
WriteLiteral(" wrote about it:\r\n");


            
            #line 22 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
Write(Html.Raw(Model.Note.Indent()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");


            
            #line 24 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
}

            
            #line default
            #line hidden

});

WriteLiteral("\r\n<p class=\"text\">\r\nAll of the collaboration will be done with Takeoff, a private" +
", secure web site that makes it easy to share and review videos.  And don\'t worr" +
"y, it\'s totally free for you.\r\n</p>\r\n");


            
            #line 29 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
 if (Model.Note.HasChars())
{

            
            #line default
            #line hidden
WriteLiteral("<p class=\"text\">Here\'s a note ");


            
            #line 31 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                         Write(Model.AddedByName);

            
            #line default
            #line hidden
WriteLiteral(" wrote for you:<br/><span class=\"video-notes\">");


            
            #line 31 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                                                                         Write(Model.Note);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n");


            
            #line 32 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<p class=\"big-link-container\">\r\n<a href=\"");


            
            #line 35 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
    Write(Model.ProductionUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Accept or Decline the Invitation</a>\r\n<div class=\"link-to-copy\">If clicking the" +
" above link didn\'t work, just copy and paste the following into your browser add" +
"ress bar:<br><b>");


            
            #line 36 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                                                                                                                    Write(Model.ProductionUrl);

            
            #line default
            #line hidden
WriteLiteral("</b></div>\r\n</p>\r\n\r\n<p class=\"text\">You can reach ");


            
            #line 39 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                         Write(Model.AddedByName);

            
            #line default
            #line hidden
WriteLiteral(" via email at <a href=\"mailto:");


            
            #line 39 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                                                         Write(Model.AddedByEmail);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 39 "..\..\Views\Email\ProductionMember-Invited-NewUser.cshtml"
                                                                                              Write(Model.AddedByEmail);

            
            #line default
            #line hidden
WriteLiteral("</a>, or by replying to this message.</p>\r\n");


        }
    }
}
#pragma warning restore 1591
