#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Email
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/ProductionAsset-New.cshtml")]
    public class ProductionAsset_New : System.Web.Mvc.WebViewPage<Email_ProductionAsset_New>
    {
        public ProductionAsset_New()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Email\ProductionAsset-New.cshtml"
  
    Layout = "~/Views/Email/Layout-ProductionBase.cshtml";
    ViewData["IncludeThumbnails"] = false;
    var changeSettingsUrl = Url.Action<AccountNotificationsController>(c => c.Index(), UrlType.AbsoluteHttps);


            
            #line default
            #line hidden

DefineSection("Subject", () => {

WriteLiteral("\r\nNew File in ");


            
            #line 9 "..\..\Views\Email\ProductionAsset-New.cshtml"
       Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlHeader", () => {

WriteLiteral("\r\n    ");


            
            #line 12 "..\..\Views\Email\ProductionAsset-New.cshtml"
Write(Model.CreatedBy);

            
            #line default
            #line hidden
WriteLiteral(" added a file in ");


            
            #line 12 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlExplanation", () => {

WriteLiteral("\r\nYou are recieving this because you are a member of Takeoff and your settings in" +
"dicate you wish to recieve an email when files are added to productions you belo" +
"g to.  Visit <a href=\"");


            
            #line 16 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                                                                                                                                                                Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                                                                                                                                                                                    Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("</a> to change this setting.\r\n");


});

WriteLiteral("\r\n");


DefineSection("Plain", () => {

WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Email\ProductionAsset-New.cshtml"
Write(Model.CreatedBy.RawHtml());

            
            #line default
            #line hidden
WriteLiteral(" added a file called ");


            
            #line 19 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                          Write(Model.OriginalFileName.RawHtml());

            
            #line default
            #line hidden
WriteLiteral(" video in ");


            
            #line 19 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                                                                     Write(Model.ProductionTitle.RawHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\nTo download, copy the following url to your browser:\r\n");


            
            #line 22 "..\..\Views\Email\ProductionAsset-New.cshtml"
Write(Model.DownloadUrl.RawHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<p class=\"big-link-container\">\r\n<a href=\"");


            
            #line 25 "..\..\Views\Email\ProductionAsset-New.cshtml"
    Write(Model.DownloadUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Download ");


            
            #line 25 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                 Write(Model.OriginalFileName.Surround("\""));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n<div class=\"link-to-copy\">If clicking the above link didn\'t work, just copy" +
" and paste the following into your browser address bar:<br><b>");


            
            #line 26 "..\..\Views\Email\ProductionAsset-New.cshtml"
                                                                                                                                    Write(Model.DownloadUrl);

            
            #line default
            #line hidden
WriteLiteral("</b></div>\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
