#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Email
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/ProductionVideo-Added-ToNonCreators.cshtml")]
    public class ProductionVideo_Added_ToNonCreators : System.Web.Mvc.WebViewPage<Email_ProductionVideo_New>
    {
        public ProductionVideo_Added_ToNonCreators()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
  
    Layout = "~/Views/Email/Layout-ProductionBase.cshtml";
    var changeSettingsUrl = Url.Action<AccountNotificationsController>(c => c.Index(), UrlType.AbsoluteHttps);


            
            #line default
            #line hidden
WriteLiteral("<a href=\"Copy%20of%20ProductionVideo-Added-ToNonCreators.cshtml\">Copy of Producti" +
"onVideo-Added-ToNonCreators.cshtml</a>\r\n");


DefineSection("Subject", () => {

WriteLiteral("\r\nNew Video Called ");


            
            #line 9 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
            Write(Model.VideoTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlHeader", () => {

WriteLiteral("\r\n    A video, ");


            
            #line 12 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
        Write(Model.VideoTitle);

            
            #line default
            #line hidden
WriteLiteral(", was added to to the ");


            
            #line 12 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                               Write(Model.ProductionTitle);

            
            #line default
            #line hidden
WriteLiteral(" production by ");


            
            #line 12 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                    Write(Model.CreatedBy);

            
            #line default
            #line hidden
WriteLiteral(".\r\n");


});

WriteLiteral("\r\n");


DefineSection("HtmlExplanation", () => {

WriteLiteral("\r\nYou are recieving this because you are a member of Takeoff and your settings in" +
"dicate you wish to recieve an email when videos are added to productions you bel" +
"og to.  Visit <a href=\"");


            
            #line 16 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                                                                                                                 Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                                                                                                                                     Write(changeSettingsUrl);

            
            #line default
            #line hidden
WriteLiteral("</a> to change this setting.\r\n");


});

WriteLiteral("\r\n");


DefineSection("Plain", () => {

WriteLiteral("\r\nA video called ");


            
            #line 19 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
          Write(Html.Raw(Model.VideoTitle));

            
            #line default
            #line hidden
WriteLiteral(" was added to to the ");


            
            #line 19 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                          Write(Html.Raw(Model.ProductionTitle));

            
            #line default
            #line hidden
WriteLiteral(" production by ");


            
            #line 19 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                                         Write(Html.Raw(Model.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral(".  To view it, please go to the following link:\r\n");


            
            #line 20 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
Write(Html.Raw(Model.WatchUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 21 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
 if (Model.Notes.HasChars())
{
            
            #line default
            #line hidden
WriteLiteral("    \r\nHere\'s some notes ");


            
            #line 23 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
             Write(Html.Raw(Model.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral(" wrote about it:\r\n");


            
            #line 24 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
Write(Html.Raw(Model.Notes.Indent()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");


            
            #line 26 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
}

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n");


            
            #line 29 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
 if (Model.Notes.HasChars())
{

            
            #line default
            #line hidden
WriteLiteral("<p class=\"text\">Here\'s some notes ");


            
            #line 31 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                             Write(Model.CreatedBy);

            
            #line default
            #line hidden
WriteLiteral(" wrote about it:<br/><span class=\"video-notes\">");


            
            #line 31 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                            Write(Model.Notes);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n");


            
            #line 32 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<p class=\"big-link-container\">\r\n<a href=\"");


            
            #line 35 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
    Write(Model.WatchUrl);

            
            #line default
            #line hidden
WriteLiteral("\">Watch It</a>\r\n<div class=\"link-to-copy\">If clicking the above link didn\'t work," +
" just copy and paste the following into your browser address bar:<br><b>");


            
            #line 36 "..\..\Views\Email\ProductionVideo-Added-ToNonCreators.cshtml"
                                                                                                                                    Write(Model.WatchUrl);

            
            #line default
            #line hidden
WriteLiteral("</b></div>\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
