#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Email
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Email/TrialExpiresTomorrow.cshtml")]
    public class TrialExpiresTomorrow : System.Web.Mvc.WebViewPage<dynamic>
    {
        public TrialExpiresTomorrow()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
  
    Layout = "~/Views/Email/Layout-Simple.cshtml";
    var url = Url.Action<SignupController>(c => c.Subscribe(null, null), UrlType.AbsoluteHttps);
    var closeUrl = Url.Action<AccountController>(c => c.Close(), UrlType.AbsoluteHttps);


            
            #line default
            #line hidden

DefineSection("Subject", () => {

WriteLiteral("\r\nYour Takeoff Trial Ends Tomorrow\r\n");


});

WriteLiteral("\r\n");


DefineSection("Plain", () => {

WriteLiteral("\r\nHi, your Takeoff free trial ends tomorrow.  We really hope you think Takeoff is" +
" worth it and want to stay with us.\r\n\r\nPlease go to the following link to purcha" +
"se Takeoff:\r\n");


            
            #line 14 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
Write(url);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("HtmlExplanation", () => {

WriteLiteral(@"
You are recieving this because you signed up for a Takeoff free trial and it's expiring tomorrow.  Since account expiration is a critical thing, there is no way to shut off these emails without closing your account.  If 
you'd like to close your account, please go to <a href=""");


            
            #line 20 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
                                                   Write(closeUrl);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 20 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
                                                              Write(closeUrl);

            
            #line default
            #line hidden
WriteLiteral("</a> or email <a href=\"mailto:support@takeoffvideo.com\">support@takeoffvideo.com<" +
"/a> and we\'ll help you.\r\n");


});

WriteLiteral(@"

<p class=""text"">
Hi, your Takeoff free trial ends tomorrow.  At that point, it will be suspended and eventually deleted.  We really hope you think Takeoff is worth it and want to stay with us.  If you have any questions, please reply to this email with them and we will respond right away.
</p>

<div class=""big-link-container"">
<a href=""");


            
            #line 28 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
    Write(url);

            
            #line default
            #line hidden
WriteLiteral("\">Purchase Takeoff</a>\r\n<div class=\"link-to-copy\">If clicking the above link didn" +
"\'t work, just copy and paste the following into your browser address bar:<br><b>" +
"");


            
            #line 29 "..\..\Views\Email\TrialExpiresTomorrow.cshtml"
                                                                                                                                    Write(url);

            
            #line default
            #line hidden
WriteLiteral("</b></div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
