#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.AccountMembers
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AccountMembers/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<AccountMembers_Index>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\AccountMembers\Index.cshtml"
  
    Layout = "~/Views/Account/Layout.cshtml";
    
    ViewData["Heading"] = "Account Members";


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n");


            
            #line 8 "..\..\Views\AccountMembers\Index.cshtml"
     if (Model.Memberships.HasItems())
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral(@"
            $(""#membersList"").dataTable({
                bJQueryUI: false,
                ""bPaginate"": false,
                ""bLengthChange"": false,
                ""bFilter"": false,
                ""bSort"": true,
                ""bInfo"": false,
                ""bAutoWidth"": false,
                aoColumns: [
                    {},
                    {},
                    {bSearchable: false, bSortable: false}//delete button
                    ]
            });
        ");

WriteLiteral("\r\n");


            
            #line 26 "..\..\Views\AccountMembers\Index.cshtml"
    }

            
            #line default
            #line hidden

});

WriteLiteral("\r\n    <p>See who is a member of your account, edit their permissions, remove them" +
", etc.</p>\r\n");


            
            #line 29 "..\..\Views\AccountMembers\Index.cshtml"
     if (Model.Memberships.IsEmpty())
    {   

            
            #line default
            #line hidden
WriteLiteral("        <p><strong>You don\'t have any users on your account right now.</strong></" +
"p>\r\n");


            
            #line 32 "..\..\Views\AccountMembers\Index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <table id=""membersList"" cellspacing=""0"" class=""data table table-striped"">
            <thead>
                <tr>
                    <th>Name</th><th>Role</th><th>Details</th>
                </tr>
            </thead>
            <tbody>
");


            
            #line 42 "..\..\Views\AccountMembers\Index.cshtml"
                 foreach (var membership in Model.Memberships)
                {
                    var detailsUrl = (Url.Action<AccountMembersController>(c => c.Details(membership.MembershipId)));

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td><a href=\"");


            
            #line 46 "..\..\Views\AccountMembers\Index.cshtml"
                                Write(detailsUrl);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 46 "..\..\Views\AccountMembers\Index.cshtml"
                                             Write(membership.MemberName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        <td>");


            
            #line 47 "..\..\Views\AccountMembers\Index.cshtml"
                       Write(membership.Role);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td><a href=\"");


            
            #line 48 "..\..\Views\AccountMembers\Index.cshtml"
                                Write(detailsUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\">View Details</a></td>\r\n                    </tr>\r\n");


            
            #line 50 "..\..\Views\AccountMembers\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n");


            
            #line 53 "..\..\Views\AccountMembers\Index.cshtml"
    
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


        }
    }
}
#pragma warning restore 1591
