#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/ClearCache.cshtml")]
    public class ClearCache : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ClearCache()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff\ClearCache.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";
    


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>Clear Memcached</h1>\r\n");


});

WriteLiteral(@"
    <p>This will clear all data held in Memcached.  Doing this unnecessarily will dramatically reduce application performace.  This is for Steve and if you don't know what you're doing, get away asshole.</p>
        <form id=""mainForm"" class=""form-horizontal"" method=""post"" action=""");


            
            #line 10 "..\..\Views\Staff\ClearCache.cshtml"
                                                                     Write(Url.Action("ClearCache","Staff"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <div class=\"");


            
            #line 11 "..\..\Views\Staff\ClearCache.cshtml"
                   Write(Html.FormActionsClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <input type=\"submit\" class=\"btn btn-danger\" value=\"Yes, I wan" +
"t to clear the app cache.\" />\r\n            </div>\r\n    </form>\r\n");


        }
    }
}
#pragma warning restore 1591
