#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/FileSummary.cshtml")]
    public class FileSummary : System.Web.Mvc.WebViewPage<dynamic>
    {
        public FileSummary()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff\FileSummary.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";
        var total = (FileTransferInfo)ViewData["total"];
        var oneHr = (FileTransferInfo)ViewData["1hr"];
        var today = (FileTransferInfo)ViewData["today"];
        var yesterday = (FileTransferInfo)ViewData["yesterday"];
        var month = (FileTransferInfo)ViewData["month"];
    

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"reportField\">\r\n        <label>Files</label>\r\n        <div>\r\n     " +
"       ");


            
            #line 12 "..\..\Views\Staff\FileSummary.cshtml"
       Write(ViewData["FileCount"]);

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n            ");


            
            #line 13 "..\..\Views\Staff\FileSummary.cshtml"
       Write(ViewData["FileSize"]);

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <label>Vide" +
"os</label>\r\n        <div>\r\n            ");


            
            #line 19 "..\..\Views\Staff\FileSummary.cshtml"
       Write(ViewData["VideoCount"]);

            
            #line default
            #line hidden
WriteLiteral(",\r\n            ");


            
            #line 20 "..\..\Views\Staff\FileSummary.cshtml"
       Write(ViewData["VideoSize"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <label>Last " +
"Hour</label>\r\n        <div>\r\n            ");


            
            #line 26 "..\..\Views\Staff\FileSummary.cshtml"
       Write(oneHr.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 27 "..\..\Views\Staff\FileSummary.cshtml"
                Write(oneHr.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 28 "..\..\Views\Staff\FileSummary.cshtml"
       Write(oneHr.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 29 "..\..\Views\Staff\FileSummary.cshtml"
                  Write(oneHr.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Today</label>\r\n        <div>\r\n            ");


            
            #line 35 "..\..\Views\Staff\FileSummary.cshtml"
       Write(today.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 36 "..\..\Views\Staff\FileSummary.cshtml"
                Write(today.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 37 "..\..\Views\Staff\FileSummary.cshtml"
       Write(today.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 38 "..\..\Views\Staff\FileSummary.cshtml"
                  Write(today.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Yesterday</label>\r\n        <div>\r\n            ");


            
            #line 44 "..\..\Views\Staff\FileSummary.cshtml"
       Write(yesterday.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 45 "..\..\Views\Staff\FileSummary.cshtml"
                Write(yesterday.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 46 "..\..\Views\Staff\FileSummary.cshtml"
       Write(yesterday.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 47 "..\..\Views\Staff\FileSummary.cshtml"
                  Write(yesterday.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>This Month</label>\r\n        <div>\r\n            ");


            
            #line 53 "..\..\Views\Staff\FileSummary.cshtml"
       Write(month.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 54 "..\..\Views\Staff\FileSummary.cshtml"
                Write(month.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 55 "..\..\Views\Staff\FileSummary.cshtml"
       Write(month.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 56 "..\..\Views\Staff\FileSummary.cshtml"
                  Write(month.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Since Beginning</label>\r\n        <div>\r\n            ");


            
            #line 62 "..\..\Views\Staff\FileSummary.cshtml"
       Write(total.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 63 "..\..\Views\Staff\FileSummary.cshtml"
                Write(total.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 64 "..\..\Views\Staff\FileSummary.cshtml"
       Write(total.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 65 "..\..\Views\Staff\FileSummary.cshtml"
                  Write(total.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n        </div>\r\n    </div>\r\n");


        }
    }
}
#pragma warning restore 1591
