#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/PrimeCache.cshtml")]
    public partial class _Views_Staff_PrimeCache_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Staff_PrimeCache_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Staff\PrimeCache.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>This\'ll load all containers into MemCached.  Nice to use after clearing " +
"cache.</p>\r\n        <form");

WriteLiteral(" id=\"mainForm\"");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 190), Tuple.Create("\"", 232)
            
            #line 5 "..\..\Views\Staff\PrimeCache.cshtml"
, Tuple.Create(Tuple.Create("", 199), Tuple.Create<System.Object, System.Int32>(Url.Action("PrimeCache","Staff")
            
            #line default
            #line hidden
, 199), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"formfield actions\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Yes, I want to prime the app cache.\"");

WriteLiteral(" />\r\n            </div>\r\n    </form>\r\n");

        }
    }
}
#pragma warning restore 1591
