#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/UsageInfo.cshtml")]
    public class UsageInfo : System.Web.Mvc.WebViewPage<dynamic>
    {
        public UsageInfo()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff\UsageInfo.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";

    var total = (FileTransferInfo)ViewData["total"];
    var oneHr = (FileTransferInfo)ViewData["1hr"];
    var today = (FileTransferInfo)ViewData["today"];
    var yesterday = (FileTransferInfo)ViewData["yesterday"];
    var month = (FileTransferInfo)ViewData["month"];


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div class=\"reportField\">\r\n        <label>Accounts</label>\r\n        <div>" +
"\r\n            ");


            
            #line 15 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["AccountCount"]);

            
            #line default
            #line hidden
WriteLiteral(" total,\r\n            ");


            
            #line 16 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["AccountVerifiedCount"]);

            
            #line default
            #line hidden
WriteLiteral(" verified\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <la" +
"bel>Users</label>\r\n        <div>\r\n            ");


            
            #line 22 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["UserCount"]);

            
            #line default
            #line hidden
WriteLiteral(" total,\r\n            ");


            
            #line 23 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["UserVerifiedCount"]);

            
            #line default
            #line hidden
WriteLiteral(" verified\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"reportField\">\r\n        <" +
"label>Encoded Videos (excluding sample)</label>\r\n        <div>\r\n            ");


            
            #line 30 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["VideoFileBytesCount"]);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n            Average: ");


            
            #line 31 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(Math.Round(((FileSize)ViewData["VideoFileBytesAvg"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB <br />\r\n            Min: ");


            
            #line 32 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(Math.Round(((FileSize)ViewData["VideoFileBytesMin"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB<br />\r\n            Max: ");


            
            #line 33 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(Math.Round(((FileSize)ViewData["VideoFileBytesMax"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB<br />\r\n            Total: ");


            
            #line 34 "..\..\Views\Staff\UsageInfo.cshtml"
              Write(Math.Round(((FileSize)ViewData["VideoFileBytesSum"]).GigaBytes, 2));

            
            #line default
            #line hidden
WriteLiteral("  GB<br />\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"reportField\">\r\n        " +
"<label>Video</label>\r\n        <div>\r\n            ");


            
            #line 41 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["VideoCountWithSample"]);

            
            #line default
            #line hidden
WriteLiteral(" total,\r\n            ");


            
            #line 42 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["VideoCount"]);

            
            #line default
            #line hidden
WriteLiteral(" excluding sample.  Other stats excluding samples: <br />\r\n            Average: ");


            
            #line 43 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(ViewData["VideoDurationAvg"]);

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n            Min: ");


            
            #line 44 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(ViewData["VideoDurationMin"]);

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n            Max: ");


            
            #line 45 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(ViewData["VideoDurationMax"]);

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n            Total: ");


            
            #line 46 "..\..\Views\Staff\UsageInfo.cshtml"
              Write(ViewData["VideoDurationSum"]);

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"reportField\">\r\n        <l" +
"abel>Video Viewings</label>\r\n        <div>\r\n            Average: ");


            
            #line 53 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(Math.Round(((FileSize)ViewData["VideoDownloadBytesAvg"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral(" MB <br />\r\n            Total: ");


            
            #line 54 "..\..\Views\Staff\UsageInfo.cshtml"
              Write(ViewData["VideoDownloadCount"]);

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 54 "..\..\Views\Staff\UsageInfo.cshtml"
                                               Write(Math.Round(((FileSize)ViewData["VideoDownloadBytesSum"]).GigaBytes, 2));

            
            #line default
            #line hidden
WriteLiteral(" GB <br />\r\n            Per Video: ");


            
            #line 55 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(ViewData["VideoDownloadPerVidAvg"]);

            
            #line default
            #line hidden
WriteLiteral(" avg, ");


            
            #line 55 "..\..\Views\Staff\UsageInfo.cshtml"
                                                           Write(ViewData["VideoDownloadPerVidMax"]);

            
            #line default
            #line hidden
WriteLiteral(" max\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <div class=\"reportField\">\r\n        <lab" +
"el>Asset Files</label>\r\n        <div>            \r\n            Average: ");


            
            #line 63 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(Math.Round(((FileSize)ViewData["AssetFileBytesAvg"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB <br />\r\n            Min: ");


            
            #line 64 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(Math.Round(((FileSize)ViewData["AssetFileBytesMin"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB<br />\r\n            Max: ");


            
            #line 65 "..\..\Views\Staff\UsageInfo.cshtml"
            Write(Math.Round(((FileSize)ViewData["AssetFileBytesMax"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral("  MB<br />\r\n            Total: ");


            
            #line 66 "..\..\Views\Staff\UsageInfo.cshtml"
              Write(ViewData["AssetFileBytesCount"]);

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 66 "..\..\Views\Staff\UsageInfo.cshtml"
                                                Write(Math.Round(((FileSize)ViewData["AssetFileBytesSum"]).GigaBytes, 2));

            
            #line default
            #line hidden
WriteLiteral(" GB<br />\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"reportField\">\r\n        <" +
"label>Asset Downloads</label>\r\n        <div>\r\n            Average: ");


            
            #line 73 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(Math.Round(((FileSize)ViewData["AssetDownloadBytesAvg"]).MegaBytes));

            
            #line default
            #line hidden
WriteLiteral(" MB <br />\r\n            Total: ");


            
            #line 74 "..\..\Views\Staff\UsageInfo.cshtml"
              Write(ViewData["AssetDownloadCount"]);

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 74 "..\..\Views\Staff\UsageInfo.cshtml"
                                               Write(Math.Round(((FileSize)ViewData["AssetDownloadBytesSum"]).GigaBytes, 2));

            
            #line default
            #line hidden
WriteLiteral(" GB <br />\r\n            Per Video: ");


            
            #line 75 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(ViewData["AssetDownloadPerFileAvg"]);

            
            #line default
            #line hidden
WriteLiteral(" avg, ");


            
            #line 75 "..\..\Views\Staff\UsageInfo.cshtml"
                                                            Write(ViewData["AssetDownloadPerFileMax"]);

            
            #line default
            #line hidden
WriteLiteral(" max\r\n        </div>\r\n    </div>\r\n\r\n\r\n\r\n\r\n        <div class=\"reportField\">\r\n    " +
"    <label>Files</label>\r\n        <div>\r\n            ");


            
            #line 85 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["FileCount"]);

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n            ");


            
            #line 86 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["FileSize"]);

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <label>Vide" +
"os</label>\r\n        <div>\r\n            ");


            
            #line 92 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["VideoCount"]);

            
            #line default
            #line hidden
WriteLiteral(",\r\n            ");


            
            #line 93 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(ViewData["VideoSize"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <label>Last " +
"Hour</label>\r\n        <div>\r\n            ");


            
            #line 99 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(oneHr.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 100 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(oneHr.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 101 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(oneHr.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 102 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(oneHr.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Today</label>\r\n        <div>\r\n            ");


            
            #line 108 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(today.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 109 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(today.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 110 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(today.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 111 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(today.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Yesterday</label>\r\n        <div>\r\n            ");


            
            #line 117 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(yesterday.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 118 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(yesterday.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 119 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(yesterday.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 120 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(yesterday.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>This Month</label>\r\n        <div>\r\n            ");


            
            #line 126 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(month.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 127 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(month.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 128 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(month.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 129 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(month.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral("). </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <labe" +
"l>Since Beginning</label>\r\n        <div>\r\n            ");


            
            #line 135 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(total.UploadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            uploads (");


            
            #line 136 "..\..\Views\Staff\UsageInfo.cshtml"
                Write(total.UploadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n            ");


            
            #line 137 "..\..\Views\Staff\UsageInfo.cshtml"
       Write(total.DownloadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n            downloads (");


            
            #line 138 "..\..\Views\Staff\UsageInfo.cshtml"
                  Write(total.DownloadSize);

            
            #line default
            #line hidden
WriteLiteral(").\r\n        </div>\r\n    </div>\r\n");


        }
    }
}
#pragma warning restore 1591
