#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff/VideoWatches.cshtml")]
    public class VideoWatches : System.Web.Mvc.WebViewPage<dynamic>
    {
        public VideoWatches()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff\VideoWatches.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral(@"

 function updateChart()
{
    $(""#chart"").attr(""src"",window.urlPrefixes.relative + ""Staff/VideoWatchesChart?dataToGraph="" + $(""#dataToGraph"").val() + ""&from="" + $(""#dateFrom"").val() + ""&to="" + $(""#dateTo"").val());
}

$(""#dateFrom, #dateTo"").datepicker(
{
   onSelect: function(dateText, inst) {
        updateChart();
   }
});

$(""#dataToGraph"").change(function()
{
        updateChart();
});

updateChart();   

");


});

WriteLiteral(@"

    <div>
        <label for=""dataToGraph"">
            What to plot:</label>
        <select id=""dataToGraph"">
            <option value=""watches"">Number of views</option>
            <option value=""bandwidth"">Download bandwidth</option>
            <option value=""duration"">Total duration watched</option>
            <option value=""users"">Users who watched video(s)</option>
            <option value=""accounts"">Accounts with video(s) watched</option>
            <option value=""productions"">Productions with a video(s) watched</option>
        </select>
    </div>
    <div>
        <label for=""dateFrom"">
            From:</label>
        <input id=""dateFrom"" type=""text"" value=""");


            
            #line 43 "..\..\Views\Staff\VideoWatches.cshtml"
                                           Write(DateTime.Now.Subtract(TimeSpan.FromDays(5)).ToString(DateTimeFormat.ShortDate));

            
            #line default
            #line hidden
WriteLiteral(" \" />\r\n        <label for=\"dateTo\">\r\n            To:</label>\r\n        <input id=\"" +
"dateTo\" type=\"text\" value=\"");


            
            #line 46 "..\..\Views\Staff\VideoWatches.cshtml"
                                         Write(DateTime.Now.ToString(DateTimeFormat.ShortDate));

            
            #line default
            #line hidden
WriteLiteral(" \" />\r\n    </div>\r\n    <div class=\"reportField\">\r\n        <div>\r\n            <img" +
" id=\"chart\" src=\"\" style=\"width: 600px; height: 400px\" />\r\n        </div>\r\n    <" +
"/div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
