#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff_Plans
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff_Plans/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<IEnumerable<Takeoff.Data.IPlan>>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Staff_Plans\Index.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 7 "..\..\Views\Staff_Plans\Index.cshtml"
    Write("Plans");

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("CssInline", () => {

WriteLiteral("\r\n");


});

WriteLiteral("\r\n<p>Pricing Plans.</p><a href=\"/staff/plans/create\">New</a>\r\n");


            
            #line 16 "..\..\Views\Staff_Plans\Index.cshtml"
     if (!Model.HasItems())
    {   

            
            #line default
            #line hidden
WriteLiteral("        <p><strong>There aren\'t any.</strong></p>\r\n");


            
            #line 19 "..\..\Views\Staff_Plans\Index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <table id=\"membersList\" cellspacing=\"0\" class=\"data table table-striped\">" +
"\r\n            <thead>\r\n                <tr>\r\n                    <th>Id</th><th>" +
"Title</th><th>Price</th>\r\n                </tr>\r\n            </thead>\r\n         " +
"   <tbody>\r\n");


            
            #line 29 "..\..\Views\Staff_Plans\Index.cshtml"
                 foreach (var plan in Model)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td><a href=\"/staff/plans/detai" +
"ls?id=");


            
            #line 32 "..\..\Views\Staff_Plans\Index.cshtml"
                                                        Write(plan.Id);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 32 "..\..\Views\Staff_Plans\Index.cshtml"
                                                                  Write(plan.Id);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        <td>");


            
            #line 33 "..\..\Views\Staff_Plans\Index.cshtml"
                       Write(plan.Title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>");


            
            #line 34 "..\..\Views\Staff_Plans\Index.cshtml"
                        Write(((double)plan.PriceInCents/100.0).ToString(NumberFormat.Currency));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");


            
            #line 36 "..\..\Views\Staff_Plans\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n");


            
            #line 39 "..\..\Views\Staff_Plans\Index.cshtml"
    
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
