#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff_Plans
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff_Plans/Sync.cshtml")]
    public class Sync : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Sync()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Staff_Plans\Sync.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Plans";


            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>This will update Recurly\'s plan database to match Takeoff\'s.  It might m" +
"odify Recurly data.</p>\r\n        <form id=\"mainForm\" method=\"post\" action=\"");


            
            #line 7 "..\..\Views\Staff_Plans\Sync.cshtml"
                                             Write(Url.Action("Sync","Staff_Plans"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <div class=\"formfield actions\">\r\n                <input type=\"sub" +
"mit\" value=\"Yes, I want to sync Recurly with Takeoff.\" />\r\n            </div>\r\n " +
"   </form>\r\n");


        }
    }
}
#pragma warning restore 1591
