#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Shared
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Account-AnonymousTrial-ProductionAccess-NotLoggedIn.cshtml")]
    public class Account_AnonymousTrial_ProductionAccess_NotLoggedIn : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Account_AnonymousTrial_ProductionAccess_NotLoggedIn()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\Account-AnonymousTrial-ProductionAccess-NotLoggedIn.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
    ViewData["PageTitle"] = "Not Available";


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>Production Not Available</h1>\r\n");


});

WriteLiteral(@"
<p class=""alert alert-error"">
    This production was created for a trial account whose owner never signed up.  Therefore, we have no way of 
    being able to safely grant you access.  If you created this production, you'll need to restart your trial and 
    sign up, which is free.  
</p>
<div class=""actions"">
    <a class=""");


            
            #line 16 "..\..\Views\Shared\Account-AnonymousTrial-ProductionAccess-NotLoggedIn.cshtml"
         Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 16 "..\..\Views\Shared\Account-AnonymousTrial-ProductionAccess-NotLoggedIn.cshtml"
                                            Write(Url.Action<SignupController>(c => c.Index(null,null, null)));

            
            #line default
            #line hidden
WriteLiteral("\">Start Over</a>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
