#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Shared
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DemoForbidden.cshtml")]
    public class DemoForbidden : System.Web.Mvc.WebViewPage<dynamic>
    {
        public DemoForbidden()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\DemoForbidden.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml"; 
    ViewData.AddBodyCss("demo-forbidden");
    ViewData["PageTitle"] = S.Demo_Forbidden_Title;
    ViewData["EnableNagBanner"] = false;//don't nag them quite yet


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 9 "..\..\Views\Shared\DemoForbidden.cshtml"
   Write(S.Demo_Forbidden_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n<p class=\"");


            
            #line 11 "..\..\Views\Shared\DemoForbidden.cshtml"
     Write(Html.AlertWarningClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 12 "..\..\Views\Shared\DemoForbidden.cshtml"
Write(S.Demo_Forbidden_Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<div class=\"actions\">\r\n<a class=\"");


            
            #line 15 "..\..\Views\Shared\DemoForbidden.cshtml"
     Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 15 "..\..\Views\Shared\DemoForbidden.cshtml"
                                        Write(Url.Action<SignupController>(c => c.Index(null, null, null)));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 15 "..\..\Views\Shared\DemoForbidden.cshtml"
                                                                                                        Write(S.Demo_Forbidden_SignupBtnText);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
