#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Shared
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layout-External-Slim.cshtml")]
    public class Layout_External_Slim : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout_External_Slim()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\Layout-External-Slim.cshtml"
  
    Layout = "~/Views/Shared/Layout-Base.cshtml";
    ViewData["MainCssLib"] = "Assets/css/theme.css";
    ViewData.AddBodyCss("app", "slim");
    this.RedefineSection("CssExternal");
    this.RedefineSection("CssInline");
    this.RedefineSection("JsExternal");
    this.RedefineSection("JsDocReady");



            
            #line default
            #line hidden

DefineSection("JsInline", () => {

WriteLiteral("\r\n");


            
            #line 13 "..\..\Views\Shared\Layout-External-Slim.cshtml"
     if (ViewData["Identity"].CastTo<Identity>() != null)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n    $.loginPing();\r\n    ");

WriteLiteral("\r\n");


            
            #line 18 "..\..\Views\Shared\Layout-External-Slim.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 19 "..\..\Views\Shared\Layout-External-Slim.cshtml"
Write(RenderSection("JsInline", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<div class=\"container\">\r\n    ");


            
            #line 22 "..\..\Views\Shared\Layout-External-Slim.cshtml"
Write(RenderPage("~/Views/Shared/Layout-External-Nav.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div role=\"main\">\r\n        ");


            
            #line 24 "..\..\Views\Shared\Layout-External-Slim.cshtml"
   Write(RenderPage("~/Views/Shared/Layout-NagBanners.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<div id=\"main-content\">\r\n\r\n");


            
            #line 27 "..\..\Views\Shared\Layout-External-Slim.cshtml"
     if (IsSectionDefined("Header"))
    {
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Layout-External-Slim.cshtml"
   Write(RenderSection("Header"));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Layout-External-Slim.cshtml"
                                
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 31 "..\..\Views\Shared\Layout-External-Slim.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</div>\r\n\t</div>\r\n\t<footer>\r\n        <p>");


            
            #line 35 "..\..\Views\Shared\Layout-External-Slim.cshtml"
      Write(S.Footer_Copyright.FormatResource(DateTime.Now.Year.ToInvariant()));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t</footer>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
