#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Shared
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Production-Login-SemiAnonymousAccess.cshtml")]
    public class Production_Login_SemiAnonymousAccess : System.Web.Mvc.WebViewPage<Productions_Login>
    {
        public Production_Login_SemiAnonymousAccess()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    ViewData["PageTitle"] = "Enter Password or Log In";
    ViewData.AddBodyCss("login", "password-protected-production");


            
            #line default
            #line hidden

DefineSection("JsDocReady", () => {

WriteLiteral("\r\n    window.views.login(");


            
            #line 9 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                  Write(Model.UseAjax.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral("); \r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n\t<h1>Access Required</h1>\r\n");


});

WriteLiteral("\r\n\r\n<div class=\"form-container\">\r\n    <h3>");


            
            #line 18 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
    Write("No Account?  Just Enter the Password");

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <p>");


            
            #line 19 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write("The production is password-protected.  If you have the password, please enter it and you'll get access without needing an account.");

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    ");


            
            #line 20 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
Write(Html.ValidationSummary(""));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <form id=\"production-password-form\" action=\"");


            
            #line 21 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                            Write(Url.Action<ProductionsController>(c => c.Login(Model.ProductionId, null), UrlType.RelativeHttps));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" class=\"form-horizontal\">\r\n        ");


            
            #line 22 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"");


            
            #line 23 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
               Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <label for=\"production-password\" class=\"control-label\">");


            
            #line 24 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                                               Write("Production Password");

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"controls\">\r\n                <input id=\"producti" +
"on-password\" type=\"password\" name=\"Password\" />\r\n                <input type=\"su" +
"bmit\" class=\"");


            
            #line 27 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                       Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");


            
            #line 27 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                                                           Write("Go");

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>\r\n\r\n<div class=\"form" +
"-container\">\r\n    <h3>Log Into Your Account</h3>\r\n    <p>If you have a Takeoff a" +
"ccount, we suggest you log in to access the production.</p>\r\n    <form action=\"");


            
            #line 36 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
              Write(Url.Action<AccountController>(c => c.LoginPost(null), UrlType.RelativeHttps));

            
            #line default
            #line hidden
WriteLiteral("\" method=\"post\" id=\"loginForm\" class=\"form-horizontal\">\r\n        ");


            
            #line 37 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 38 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write(Html.HiddenFor(m => m.TimezoneOffset));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 39 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write(Html.HiddenFor(m => m.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 40 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
   Write(Html.TextBoxControlGroupFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t    <div class=\"");


            
            #line 41 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
            Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\" id=\"password-group\">\r\n            ");


            
            #line 42 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
       Write(Html.ControlLabelFor(m => m.Password, S.Login_PasswordLabel));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"controls\">\r\n                ");


            
            #line 44 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
           Write(Html.TextBoxFor(m => m.Password, new { type = "password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \t    <a class=\"help-inline\" href=\"");


            
            #line 45 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                      Write(Url.Action<AccountController>(c => c.PasswordReset(null)));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 45 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                                                                                   Write(S.Login_ForgotPasswordLink);

            
            #line default
            #line hidden
WriteLiteral("</a>            \r\n            </div>\r\n\t    </div>\r\n\t    <div class=\"");


            
            #line 48 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
            Write(Html.ControlGroupClass());

            
            #line default
            #line hidden
WriteLiteral("\" id=\"remember-me-group\">\r\n            <div class=\"controls checkbox\">\r\n         " +
"   ");


            
            #line 50 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
       Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 51 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
       Write(Html.LabelFor(m => m.RememberMe, S.Login_RememberMeLabel));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\t    </div>\r\n        <div class=\"");


            
            #line 54 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
               Write(Html.FormActionsClass());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <input class=\"");


            
            #line 55 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                     Write(Html.PrimaryButtonClass());

            
            #line default
            #line hidden
WriteLiteral("\" type=\"submit\" value=\"");


            
            #line 55 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
                                                                      Write(S.Login_SubmitBtnText);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            <span>");


            
            #line 56 "..\..\Views\Shared\Production-Login-SemiAnonymousAccess.cshtml"
             Write(S.Login_SignupLink.FormatResource(Html.StartTag("a").Href(Url.Action<SignupController>(c => c.Index(null, null, null)))));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </div>\r\n    </form>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
