#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Shared
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SuccessMessage.cshtml")]
    public class SuccessMessage : System.Web.Mvc.WebViewPage<Message>
    {
        public SuccessMessage()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\SuccessMessage.cshtml"
  
    //this page is used to provide simple error to users, such as validation or account problems.  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml"; 
    Html.DisableNagBanners();
    if ( Model.PageTitle.HasChars())
    {
        ViewData["PageTitle"] = Model.PageTitle;
    }
    else if ( Model.Heading.HasChars())
    {
        ViewData["PageTitle"] = Model.Heading;            
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Header", () => {

WriteLiteral("\r\n");


            
            #line 18 "..\..\Views\Shared\SuccessMessage.cshtml"
     if (Model.Heading.HasChars())
    {

            
            #line default
            #line hidden
WriteLiteral("        <h1>");


            
            #line 20 "..\..\Views\Shared\SuccessMessage.cshtml"
       Write(Model.Heading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 21 "..\..\Views\Shared\SuccessMessage.cshtml"
    }

            
            #line default
            #line hidden

});

WriteLiteral("\r\n\r\n<p class=\"");


            
            #line 24 "..\..\Views\Shared\SuccessMessage.cshtml"
     Write(Html.AlertSuccessClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 24 "..\..\Views\Shared\SuccessMessage.cshtml"
                                    Write(Model.Text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


        }
    }
}
#pragma warning restore 1591
