#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Signup
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Signup/AlreadySignedUp.cshtml")]
    public partial class AlreadySignedUp : System.Web.Mvc.WebViewPage<dynamic>
    {
        public AlreadySignedUp()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Signup\AlreadySignedUp.cshtml"
  
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml"; 
        Html.DisableNagBanners();



            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n<h1>");


            
            #line 8 "..\..\Views\Signup\AlreadySignedUp.cshtml"
Write(S.Signup_AlreadySignedUp_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n\r\n<p class=\"");


            
            #line 11 "..\..\Views\Signup\AlreadySignedUp.cshtml"
     Write(Html.AlertWarningClass(true));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 11 "..\..\Views\Signup\AlreadySignedUp.cshtml"
                                    Write(S.Signup_AlreadySignedUp_Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


        }
    }
}
#pragma warning restore 1591
