#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takeoff.Views.Staff_Accounts
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Mediascend;
    using Mediascend.Web;
    using MvcContrib;
    using Takeoff;
    using Takeoff.Controllers;
    using Takeoff.Data;
    using Takeoff.Models;
    using Takeoff.Mvc;
    using Takeoff.Resources;
    using Takeoff.ViewModels;
    using Takeoff.Views.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Staff_Accounts/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<Staff_Accounts_Details>
    {
        public Details()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Staff_Accounts\Details.cshtml"
  
    Layout = "~/Views/Staff/staff-layout.cshtml";


            
            #line default
            #line hidden

DefineSection("Header", () => {

WriteLiteral("\r\n    <h1>");


            
            #line 7 "..\..\Views\Staff_Accounts\Details.cshtml"
    Write("Account #");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 7 "..\..\Views\Staff_Accounts\Details.cshtml"
                  Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("JsDocReady", () => {

WriteLiteral(@"
$(""#impersonate"").click(function (e) {
    var message = ""Do you want to log in as this account owner?  You will be able to do everything they can do.  If you want to come back to the staff section you'll have to log out then back in under your normal account.  Remember impersonating is not an excuse for spying."";
    if (!confirm(message)) {
        e.preventDefault();
        return false;
    }
});
");


});

WriteLiteral("\r\n");


DefineSection("CssInline", () => {

WriteLiteral("\r\n");


});

WriteLiteral("\r\n<div>\r\n<a href=\"");


            
            #line 24 "..\..\Views\Staff_Accounts\Details.cshtml"
    Write(Url.Action("Edit", "Staff_Accounts", Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\">Edit Account</a> &nbsp; <a href=\"");


            
            #line 24 "..\..\Views\Staff_Accounts\Details.cshtml"
                                                                                      Write(Url.Action("Delete", "Staff_Accounts", Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\">Delete Account</a>\r\n</div>\r\n<div>\r\n    <label>Owner:</label>\r\n    ");


            
            #line 28 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Owner.DisplayName);

            
            #line default
            #line hidden
WriteLiteral(" &nbsp; <a href=\"mailto:");


            
            #line 28 "..\..\Views\Staff_Accounts\Details.cshtml"
                                               Write(Model.Owner.Email);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 28 "..\..\Views\Staff_Accounts\Details.cshtml"
                                                                   Write(Model.Owner.Email);

            
            #line default
            #line hidden
WriteLiteral("</a> &nbsp; <a href=\"");


            
            #line 28 "..\..\Views\Staff_Accounts\Details.cshtml"
                                                                                                          Write(Url.ActionDetails("Staff_Users",Model.Owner.Id));

            
            #line default
            #line hidden
WriteLiteral("\">View/Edit User Details</a> &nbsp; <a id=\"impersonate\" href=\"");


            
            #line 28 "..\..\Views\Staff_Accounts\Details.cshtml"
                                                                                                                                                                                                                        Write(Url.Action("Impersonate","Staff_Users", new { id = Model.Owner.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">Impersonate</a>\r\n</div>\r\n");


            
            #line 30 "..\..\Views\Staff_Accounts\Details.cshtml"
 if (Model.Account.IsSubscribed())
{

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    <label>Recurly Link:</label>\r\n    <a href=\"");


            
            #line 34 "..\..\Views\Staff_Accounts\Details.cshtml"
        Write(Model.RecurlyUrl);

            
            #line default
            #line hidden
WriteLiteral("\" target=\"_blank\">View Account in Recurly</a>\r\n</div>\r\n");


            
            #line 36 "..\..\Views\Staff_Accounts\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    <label>Account Status:</label>\r\n    ");


            
            #line 39 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.Status);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n    <label>Plan:</label>\r\n");


            
            #line 43 "..\..\Views\Staff_Accounts\Details.cshtml"
 if ( Model.Account.Plan == null )
{

            
            #line default
            #line hidden
WriteLiteral("    <span>NONE!</span>\r\n");


            
            #line 46 "..\..\Views\Staff_Accounts\Details.cshtml"
}
else
{
   
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.Plan.Id);

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Staff_Accounts\Details.cshtml"
                         
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <label>Created:</label>\r\n    ");


            
            #line 54 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.CreatedOn);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


            
            #line 57 "..\..\Views\Staff_Accounts\Details.cshtml"
 if ( Model.Account.CurrentBillingPeriodStartedOn.HasValue )
{

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    <label>Current Billing Period Started On:</label>\r\n    ");


            
            #line 61 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.CurrentBillingPeriodStartedOn.Value.ToString(DateTimeFormat.ShortDateTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


            
            #line 63 "..\..\Views\Staff_Accounts\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 65 "..\..\Views\Staff_Accounts\Details.cshtml"
 if ( Model.Account.CurrentBillingPeriodEndsOn().HasValue )
{

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    <label>Current Billing Period Ends On:</label>\r\n    ");


            
            #line 69 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.CurrentBillingPeriodEndsOn().Value.ToString(DateTimeFormat.ShortDateTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


            
            #line 71 "..\..\Views\Staff_Accounts\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div>\r\n<label>Trial Period Ends:</label>\r\n");


            
            #line 76 "..\..\Views\Staff_Accounts\Details.cshtml"
 if (!Model.Account.TrialPeriodEndsOn.HasValue)
{

            
            #line default
            #line hidden
WriteLiteral("    <span>N/A</span>\r\n");


            
            #line 79 "..\..\Views\Staff_Accounts\Details.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <span>");


            
            #line 82 "..\..\Views\Staff_Accounts\Details.cshtml"
     Write(Model.Account.TrialPeriodEndsOn);

            
            #line default
            #line hidden
WriteLiteral(" - ");


            
            #line 82 "..\..\Views\Staff_Accounts\Details.cshtml"
                                        Write(Model.Account.DaysLeftInTrial);

            
            #line default
            #line hidden
WriteLiteral(" days left</span>\r\n");


            
            #line 83 "..\..\Views\Staff_Accounts\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n\r\n\r\n<div>\r\n    <label>Productions:</label>\r\n    ");


            
            #line 91 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.ProductionCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n    <label>Videos Total:</label>\r\n    ");


            
            #line 95 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.VideoCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n    <label>Videos In Billing Cycle:</label>\r\n    ");


            
            #line 99 "..\..\Views\Staff_Accounts\Details.cshtml"
Write(Model.Account.VideosAddedInBillingCycle);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");



WriteLiteral("\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
